global:
  scrape_interval: 10s
  external_labels:
    host_node: '##inventory_hostname##'
    testnet: '##testnet##'

scrape_configs:
  - job_name: 'prometheus-##testnet##'
    static_configs:
      - targets: 
        - 'localhost:9090'
        labels:
          appname: 'prometheus'
          instance: '##inventory_hostname##'

  - job_name: 'node-exporter-##testnet##'
    static_configs:
      - targets: 
        - 'node-exporter:9100'
        labels:
          appname: 'node-exporter'
          instance: '##inventory_hostname##'

  - job_name: 'discovery-##testnet##'
    file_sd_configs:
    - files:
      - '/etc/prometheus/file_sd/*.yml'


