global:
  scrape_interval: 15s
  external_labels:
    host_node: '##inventory_hostname##'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - 'localhost:9090'
        labels:
          appname: 'prometheus'
          instance: '##inventory_hostname##'

  - job_name: 'node-exporter'
    static_configs:
      - targets: 
        - 'node-exporter:9100'
        labels:
          appname: 'node-exporter'
          instance: '##inventory_hostname##'

  - job_name: 'cadvisor'
    static_configs:
      - targets: 
        - 'cadvisor:8080'
        labels:
          appname: 'cadvisor'
          instance: '##inventory_hostname##'

  - job_name: 'discovery'
    file_sd_configs:
    - files:
      - '/etc/prometheus/file_sd/*.yml'


