global:
  scrape_interval: 10s
  external_labels:
    cluster: '##inventory_hostname##'

scrape_configs:
  - job_name: '##inventory_hostname##'
    static_configs:
      - targets: 
        - 'localhost:9090'
        labels:
          instance: 'prometheus'

      - targets: 
        - 'localhost:9100'
        labels:
          instance: 'node-exporter'

    file_sd_configs:
    - files:
      - '/etc/prometheus/file_sd/*.yml'


