- name: Change setting /etc/ufw/after.rules
  register: changedDocker
  blockinfile:
    path: /etc/ufw/after.rules
    block: |
      *filter
      :ufw-user-input - [0:0]
      :DOCKER-USER - [0:0]

      # ufw in front of docker while allowing all inter-container traffic

      -A DOCKER-USER -j RETURN -s 10.0.0.0/8
      -A DOCKER-USER -j RETURN -s 172.16.0.0/12
      -A DOCKER-USER -j RETURN -s 192.168.0.0/16

      -A DOCKER-USER -j ufw-user-input
      -A DOCKER-USER -j RETURN

      COMMIT
    state: present

- name: Backup /etc/ufw/before.init file
  when: changedDocker.changed == true
  copy:
    remote_src: true
    src: /etc/ufw/before.init
    dest: "/etc/ufw/before.init.backup-{{ lookup('pipe', 'date +%s') }}"

- name: Remove /etc/ufw/before.init file
  when: changedDocker.changed == true
  file:
    path: /etc/ufw/before.init
    state: absent

- name: Add /etc/ufw/before.init file with new changes
  when: changedDocker.changed == true
  blockinfile:
    create: 'yes'
    mode: '750'
    path: /etc/ufw/before.init
    block: |
      set -e

      case "$1" in
      start)
          # typically required
          ;;
      stop)
          # typically required
          iptables -F DOCKER-USER || true
          iptables -A DOCKER-USER -j RETURN || true
          iptables -X ufw-user-input || true
          ;;
      status)
          # optional
          ;;
      flush-all)
          # optional
          ;;
      *)
          echo "'$1' not supported"
          echo "Usage: before.init {start|stop|flush-all|status}"
          ;;        
      esac

- name: Disable ipv6
  lineinfile:
    dest: /etc/default/ufw
    regexp: '^IPV6='
    line: 'IPV6=no'

- name: Reload UFW
  when: changedDocker.changed == true
  ufw:
    state: reloaded
