- name: Geth firewall management
  hosts: [geth]
  gather_facts: false
  become: true
  vars:
    subnet_ips: []

  tasks:
    - name: Include secret variables
      include_vars: "{{secrets_file}}"

    - name: Reset UFW
      ufw:
        state: reset

    - name: Configure ufw docker
      import_tasks: configure_ufw_docker.yml

    - name: Allow TCP ports through firewall
      ufw:
        rule: allow
        port: "22,30303"
        proto: "tcp"
        comment: "Allow SSH, Go Ethereum TCP"

    - name: Allow UDP ports through firewall
      ufw:
        rule: allow
        port: "30303"
        proto: "udp"
        comment: "Allow Go Ethereum UDP"

    - name: Run python to get subnet ips
      delegate_to: localhost
      throttle: 1
      run_once: true
      become: false
      command: "{{ansible_python_interpreter}} main.py {{ inventory_dir }}/inventory.ini geth"
      register: python_result

    - name: Set variables
      set_fact:
        subnet_ips: "{{python_result.stdout}}"

    - name: Set subnet_ips variables
      set_fact:
        subnet_ips: "{{subnet_ips[inventory_hostname]}}"

    - name: Allow GETH API 8545
      shell: "echo -n '{{ subnet_ips | join(',') }}' | sudo xargs -d ',' -I {} ufw allow from {} to any port 8545 proto tcp comment 'Allow GETH API 8545'"

    - name: Allow GETH WS API 8546
      shell: "echo -n '{{ subnet_ips | join(',') }}' | sudo xargs -d ',' -I {} ufw allow from {} to any port 8546 proto tcp comment 'Allow GETH WS API 8546'"

    - name: Allow GETH AUTH RPC API 8551
      shell: "echo -n '{{ subnet_ips | join(',') }}' | sudo xargs -d ',' -I {} ufw allow from {} to any port 8551 proto tcp comment 'Allow GETH AUTH RPC API 8551'"

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny
        logging: 'on'
