---
- name: Create mnemonic
  shell: "docker run --rm ethstaker/eth-val-tools mnemonic"
  register: mnemonic_output

- name: Add mnenomic to mnemonics.yaml
  blockinfile:
    path: "{{ local_custom_config_data_host_dir }}/{{test.key}}/mnemonics.yaml"
    block: |
      # {{item}}
      - mnemonic: "{{mnemonic_output.stdout}}"
        count: {{VALIDATORS_PER_INSTANCE}}
    marker: ""

- name: Add mnenomic to secret_mnemonics.yaml
  blockinfile:
    path: "{{ local_custom_config_data_host_dir }}/{{test.key}}/secret_mnemonics.yaml"
    block: |
      {{item}}: "{{mnemonic_output.stdout}}"
    marker: ""
