- name: Initialize bootnode enr file
  hosts: all[0]
  connection: local
  gather_facts: false
  tasks:
    - name: Create enr file or clear if exists
      copy:
        dest: "{{ inventory_dir }}/group_vars/enr.yml"
        content: "bootnode_enrs:"
