- name: Initialize bootnode enr file
  hosts: all[0]
  connection: local
  gather_facts: false
  tasks:
    - name: Create enr_all file or clear if exists
      copy:
        dest: "{{ inventory_dir }}/group_vars/enr_all.yml"
        content: "bootnode_enrs:"

    - name: Create enr_groups file or clear if exists
      copy:
        dest: "{{ inventory_dir }}/group_vars/enr_groups.yml"
        content: ""
