---
- name: Creates enr dir
  file:
    path: "{{enr_groups_all_path}}"
    state: directory

- name: Create enr_all file or clear if exists
  copy:
    dest: "{{enr_all_file}}"
    content: "bootnode_enrs:"

- name: Create enr_groups file or clear if exists
  copy:
    dest: "{{enr_groups_file}}"
    content: ""
