---
- name: Copy config file
  copy:
    src: "{{ local_postmerge_custom_config_data_host_dir }}/"
    dest: "{{ local_custom_config_data_host_dir }}/{{runningTest}}/config"

- name: Replace variable in conf file
  replace:
    path: "{{ local_custom_config_data_host_dir }}/{{runningTest}}/config/values.env"
    regexp: "{{item.0}}"
    replace: "{{item.1}}"
  loop:
    - ["##MIN_GENESIS_ACTIVE_VALIDATOR_COUNT##", "{{groups[runningTest + '_validator']|length * VALIDATORS_PER_INSTANCE}}"]
    - ["##MIN_GENESIS_TIME##", "{{MIN_GENESIS_TIME}}"]
    - ["##POSTMERGE_CHAIN_ID##", "{{POSTMERGE_CHAIN_ID}}"]

- name: Set mnemonics path
  set_fact:
    MNEMONICS_PATH: "{{ local_custom_config_data_host_dir }}/{{runningTest}}/config/cl"

- name: Create empty mnemonics.yaml
  copy:
    dest: "{{ MNEMONICS_PATH }}/mnemonics.yaml"
    content: ""

- name: Create empty secret_mnemonics.yaml
  copy:
    dest: "{{ MNEMONICS_PATH }}/secret_mnemonics.yaml"
    content: ""

- name: Generate mnenomic and add to file
  include_tasks: tasks/generate_mnemonics.yml
  loop: "{{groups[runningTest + '_validator']}}"

- name: Generate genesis state
  shell: "docker run --user root --rm -v {{local_custom_config_data_host_dir}}/{{runningTest}}/data:/data -v {{local_custom_config_data_host_dir}}/{{runningTest}}/config:/config gathecageorge/merged_testnet_tools:latest all noserver"
  register: ret
  failed_when: ret.stderr == ''
