---
- name: Copy config file
  copy:
    src: "{{ local_postmerge_custom_config_data_host_dir }}/"
    dest: "{{ local_custom_config_data_host_dir }}/{{runningTest}}/config"

- name: Replace variable in conf file
  replace:
    path: "{{ local_custom_config_data_host_dir }}/{{runningTest}}/config/values.env"
    regexp: "{{item.0}}"
    replace: "{{item.1}}"
  loop:
    - ["##MIN_GENESIS_ACTIVE_VALIDATOR_COUNT##", "{{groups[runningTest + '_validator']|length * VALIDATORS_PER_INSTANCE}}"]
    - ["##POSTMERGE_CHAIN_ID##", "{{POSTMERGE_CHAIN_ID}}"]
    - ["##EL_AND_CL_MNEMONIC##", "{{EL_AND_CL_MNEMONIC}}"]
    - ["##MIN_GENESIS_TIME##", "{{MIN_GENESIS_TIME}}"]

- name: Creates data dir
  file:
    path: "{{local_custom_config_data_host_dir}}/{{runningTest}}/data"
    state: directory

- name: Generate genesis state
  shell: "docker run -u 1000 --rm -v {{local_custom_config_data_host_dir}}/{{runningTest}}/data:/data -v {{local_custom_config_data_host_dir}}/{{runningTest}}/config:/config ethpandaops/ethereum-genesis-generator:latest all"
  register: ret
  failed_when: ret.stderr == ''

# - name: Generate genesis state
#   shell: "docker run -u 1000 --rm -v {{local_custom_config_data_host_dir}}/{{runningTest}}/data:/data -v {{local_custom_config_data_host_dir}}/{{runningTest}}/config:/config gathecageorge/merged_testnet_tools:latest all noserver"
#   register: ret
#   failed_when: ret.stderr == ''

- name: Create deposit_contract_block_hash.txt
  copy:
    dest: "{{ local_custom_config_data_host_dir }}/{{runningTest}}/data/custom_config_data/deposit_contract_block_hash.txt"
    content: "0x0000000000000000000000000000000000000000000000000000000000000000"
