---
- name: Copy config file
  copy:
    src: "{{ local_premerge_custom_config_data_host_dir }}/config.yaml"
    dest: "{{ local_custom_config_data_host_dir }}/{{runningTest}}"

- name: Replace variable in conf file
  replace:
    path: "{{ local_custom_config_data_host_dir }}/{{runningTest}}/config.yaml"
    regexp: "{{item.0}}"
    replace: "{{item.1}}"
  loop:
    - ["##CONFIG_NAME##", "{{TESTS[runningTest][0]}}"]
    - ["##MIN_GENESIS_ACTIVE_VALIDATOR_COUNT##", "{{groups[runningTest + '_validator']|length * VALIDATORS_PER_INSTANCE}}"]
    - ["##DATE_FULL##", "{{DATE_FULL.stdout}}"]
    - ["##MIN_GENESIS_TIME##", "{{MIN_GENESIS_TIME}}"]
    - ["##GENESIS_DELAY##", "{{GENESIS_DELAY}}"]
    - ["##SECONDS_PER_SLOT##", "{{TESTS[runningTest][1]}}"]
    - ["##NETWORK##", "{{NETWORK}}"]
    - ["##DEPOSIT_CHAIN_ID##", "{{DEPOSIT_CHAIN_ID}}"]
    - ["##DEPOSIT_NETWORK_ID##", "{{DEPOSIT_NETWORK_ID}}"]
    - ["##DEPOSIT_CONTRACT_ADDRESS##", "{{transaction_hash_details.contract_address}}"]

- name: Create deploy_block.txt
  copy:
    dest: "{{ local_custom_config_data_host_dir }}/{{runningTest}}/deploy_block.txt"
    content: |
      {{transaction_hash_details.block_number}}

- name: Create deposit_contract.txt
  copy:
    dest: "{{ local_custom_config_data_host_dir }}/{{runningTest}}/deposit_contract.txt"
    content: |
      {{transaction_hash_details.contract_address}}

- name: Create deposit_contract_block_hash.txt
  copy:
    dest: "{{ local_custom_config_data_host_dir }}/{{runningTest}}/deposit_contract_block_hash.txt"
    content: |
      {{transaction_hash_details.block_hash}}

- name: Create mnemonics.yaml
  copy:
    dest: "{{ local_custom_config_data_host_dir }}/{{runningTest}}/mnemonics.yaml"
    content: |
      - mnemonic: "{{EL_AND_CL_MNEMONIC}}"  # a 24 word BIP 39 mnemonic
        count: {{groups[runningTest + '_validator']|length * VALIDATORS_PER_INSTANCE}}

- name: Generate genesis state
  shell: "docker run --user $(id -u):$(id -u) --network host --rm -v {{local_custom_config_data_host_dir}}/{{runningTest}}:/data gathecageorge/eth2-testnet-genesis:latest phase0 --config /data/config.yaml --eth1-block {{transaction_hash_details.block_hash}} --mnemonics /data/mnemonics.yaml --timestamp {{MIN_GENESIS_TIME - GENESIS_DELAY}} --tranches-dir /data/tranches --state-output /data/genesis.ssz"
