---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: upgrade=dist

- name: Check if docker is installed
  stat: path=/usr/bin/docker
  register: dockerexist

- name: Configure and install docker
  when: dockerexist.stat.exists == False
  block:
    - name: Install dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gnupg-agent
      
    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - docker-ce
        - docker-ce-cli 
        - containerd.io
        - python3-docker

    - name: Add user to docker group
      user:
        name: "{{ansible_user}}"
        group: docker

    - name: Unconditionally reboot the machine with all defaults when docker is installed
      reboot:

- name: Configure and install docker-compose
  vars:
    docker_compose_version: "v2.15.1"
  block:
    - name: Check docker-compose {{ docker_compose_version }} is installed
      stat: path=/usr/local/bin/docker-compose-{{ docker_compose_version }}
      register: docker_compose

    - name: Download docker-compose {{ docker_compose_version }}
      get_url:
        url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
        dest: ~/docker-compose
        mode: '+x'
      when: docker_compose.stat.exists == False

    - name: Move docker-compose to /usr/local/bin/docker-compose-{{ docker_compose_version }}
      command: mv ~/docker-compose /usr/local/bin/docker-compose-{{ docker_compose_version }}
      when: docker_compose.stat.exists == False

    - name: Create a symbolic link
      ansible.builtin.file:
        src: /usr/local/bin/docker-compose-{{ docker_compose_version }}
        dest: /usr/local/bin/docker-compose
        state: link
      when: docker_compose.stat.exists == False

- name: Create docker monitoring network
  docker_network:
    name: "{{ docker_monitoring_network }}"
