---
- name: Recreate validator_node_dir and register metrics
  shell: |
    # Stop validator container and unregister metrics
    sudo rm -f {{ prometheus_file_sd_dir }}/validator.yml
    docker rm -f {{validator_container_name}} || true

    # Create validator_node_dir
    mkdir -p {{validator_node_dir}}
    chown -R "{{ validator_user_id }}" "{{ validator_node_dir }}"

    # Register validator metrics to prometheus
    if [[ '{{ eth2_client_name }}' = 'lighthouse' || '{{ eth2_client_name }}' = 'prysm' ]]; then
    cat > {{ prometheus_file_sd_dir }}/validator.yml << EOF
    - labels:
        appname: validator
        testnet: {{ TESTS[runningTest][0] }}
      targets:
      - {{ validator_container_name }}:{{ validator_metrics_port }}
    EOF
    fi

    
- name: Start Eth2 validator client container
  docker_container:
    name: "{{ validator_container_name }}"
    state: started
    image: "{{ validator_image_name }}"
    pull: true
    restart_policy: unless-stopped
    memory_swappiness: 0
    network_mode: "{{ docker_monitoring_network }}"
    restart: "{{ restart_container_if_exists | default(false) }}"
    log_options: "{{ common_log_options }}"
    log_driver: "{{ common_log_driver }}"
    volumes: "{{validator_volumes}}"
    memory: "{{validator_memory}}"
    memory_swap: "{{validator_memory}}"
    command: "{{ validator_start_args }}"
    env: "{{ validator_env | default({}) }}"
    user: "{{ validator_user_id }}"
    labels: "{{ testnet_labels }}"
