- name: Start besu/eth1 node
  hosts: geth
  gather_facts: false
  tasks:
    - name: Include besu variables
      include_vars: "{{inventory_dir}}/group_vars/eth1client_besu.yml"

    - name: Creates eth1 data dir
      file:
        path: "{{eth1_node_dir}}"
        state: directory

    - name: Modify permissions to match user-group inside docker image
      shell: chown -R "{{ eth1_user_id }}" "{{ eth1_node_dir }}"
      become: true

    - name: Start Eth1 container
      docker_container:
        name: "{{ eth1_container_name }}"
        state: started
        image: "{{ eth1_image_name }}"
        pull: true
        restart_policy: unless-stopped
        memory_swappiness: 0
        kernel_memory: "{{eth1_kernel_memory}}"
        network_mode: host
        restart: "{{ restart_container_if_exists | default(false) }}"
        log_options: "{{ common_log_options }}"
        log_driver: "{{ common_log_driver }}"
        volumes: "{{eth1_volumes}}"
        memory: "{{eth1_memory}}"
        memory_swap: "{{eth1_memory}}"
        command: "{{ eth1_start_args }}"
        env: "{{ eth1_env | default({}) }}"
        user: "{{ eth1_user_id }}"

    - name: Register besu metrics to prometheus
      copy:
        dest: "{{ prometheus_file_sd_dir }}/besu.yml"
        content: |
          - labels:
              appname: {{ eth1_container_name }}
            targets:
            - dockerhost:{{eth1_metrics_port}}
      when: eth1_metrics_port | default('') != ''


