---
- name: Setup prometheus and run
  shell: |
    mkdir -p {{ prometheus_data_dir }} {{ prometheus_config_dir }}/file_sd
    chown -R {{ ansible_user }} {{ prometheus_data_dir }}
    chown -R {{ ansible_user }} {{ prometheus_config_dir }}

    # Create config file
    cat > {{ prometheus_config_dir }}/config.yml << EOF
    global:
      scrape_interval: 15s
      external_labels:
        host_node: '{{inventory_hostname}}'

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: 
            - 'localhost:9090'
            labels:
              appname: 'prometheus'
              instance: '{{inventory_hostname}}'

      - job_name: 'node-exporter'
        static_configs:
          - targets: 
            - 'node-exporter:9100'
            labels:
              appname: 'node-exporter'
              instance: '{{inventory_hostname}}'

      - job_name: 'cadvisor'
        static_configs:
          - targets: 
            - 'cadvisor:8080'
            labels:
              appname: 'cadvisor'
              instance: '{{inventory_hostname}}'

      - job_name: 'discovery'
        file_sd_configs:
        - files:
          - '/etc/prometheus/file_sd/*.yml'

    EOF

    # Append remote write if set
    if [ '{{ remote_write_url }}' != '' ]; then
    cat >> {{ prometheus_config_dir }}/config.yml << EOF
    remote_write:
      - url: "{{ remote_write_url }}"

    EOF
    fi

    # Run prometheus
    if [ '{{ enable_remote_receiver }}' = 'true' ]; then
    docker rm -f {{ prometheus_container_name }} || true && docker run -d --log-driver {{common_log_driver}} --log-opt tag="{{'{{'}}.ImageName{{'}}'}}|{{'{{'}}.Name{{'}}'}}|{{'{{'}}.ImageFullID{{'}}'}}|{{'{{'}}.FullID{{'}}'}}|default" --name {{ prometheus_container_name }} -u {{ prometheus_user_id }} -v {{ prometheus_data_dir }}:/prometheus -v {{ prometheus_config_dir }}:/etc/prometheus -p {{public_ip_address}}:9090:9090 --restart unless-stopped --network {{ docker_monitoring_network }} {{ prometheus_image_name }}  --enable-feature=remote-write-receiver {{ prometheus_start_args }}
    else
    docker rm -f {{ prometheus_container_name }} || true && docker run -d --log-driver {{common_log_driver}} --log-opt tag="{{'{{'}}.ImageName{{'}}'}}|{{'{{'}}.Name{{'}}'}}|{{'{{'}}.ImageFullID{{'}}'}}|{{'{{'}}.FullID{{'}}'}}|default" --name {{ prometheus_container_name }} -u {{ prometheus_user_id }} -v {{ prometheus_data_dir }}:/prometheus -v {{ prometheus_config_dir }}:/etc/prometheus -p {{public_ip_address}}:9090:9090 --restart unless-stopped --network {{ docker_monitoring_network }} {{ prometheus_image_name }} {{ prometheus_start_args }}
    fi

