- name: Start Register dc local logging
  hosts: [dc_local]
  gather_facts: true
  become: true
  serial: 20
  tasks:
    - name: Delete existing configurations
      shell: rm -rf /etc/prometheus/file_sd/discovery*

    - name: Register node exporter prometheus
      copy:
        dest: "/etc/prometheus/file_sd/discovery_{{ item }}_9100.yml"
        group: prometheus
        owner: root
        mode: 0640
        content: |
          - labels:
              env: {{ item }}
              instance: {{ item }}_node_exporter
            targets:
            - {{ hostvars[item].ansible_host }}:9100
      loop: "{{ query('inventory_hostnames', 'all') }}"
      when: hostvars[item].dc_local_host | default('empty') == inventory_hostname

    - name: Register beacon node prometheus
      copy:
        dest: "/etc/prometheus/file_sd/discovery_{{ item }}_{{ beacon_metrics_port }}.yml"
        group: prometheus
        owner: root
        mode: 0640
        content: |
          - labels:
              env: {{ item }}
              instance: {{ item }}_beacon
            targets:
            - {{ hostvars[item].ansible_host }}:{{ beacon_metrics_port }}
      loop: "{{ query('inventory_hostnames', 'beacon') }}"
      when: hostvars[item].dc_local_host | default('empty') == inventory_hostname

    - name: Register validator node prometheus
      copy:
        dest: "/etc/prometheus/file_sd/discovery_{{ item }}_{{ validator_metrics_port }}.yml"
        group: prometheus
        owner: root
        mode: 0640
        content: |
          - labels:
              env: {{ item }}
              instance: {{ item }}_validator
            targets:
            - {{ hostvars[item].ansible_host }}:{{ validator_metrics_port }}
      loop: "{{ query('inventory_hostnames', 'validator') }}"
      when: hostvars[item].dc_local_host | default('empty') == inventory_hostname

- name: Start Register global federation logging
  hosts: [global_federation]
  gather_facts: true
  become: true
  serial: 20
  tasks:
    - name: Delete existing configurations
      shell: rm -rf /etc/prometheus/file_sd/discovery*

    - name: Register dc local prometheus
      copy:
        dest: "/etc/prometheus/file_sd/discovery_{{ item }}_9090.yml"
        group: prometheus
        owner: root
        mode: 0640
        content: |
          - labels:
              env: {{ item }}
              instance: {{ item }}_prometheus
            targets:
            - {{ hostvars[item].ansible_host }}:9090
      loop: "{{ query('inventory_hostnames', 'dc_local') }}"
      when: hostvars[item].global_federation_host | default('empty') == inventory_hostname
