- name: Start geth/eth1 node
  hosts: eth1
  gather_facts: true
  tasks:
    - name: Get info on container if running
      docker_container_info:
        name: "{{ eth1_container_name }}"
      register: result

    - name: Creates eth1 dir
      when: result.exists == False
      file:
        path: "{{eth1_node_dir}}"
        state: directory

    - name: Modify permissions to match user-group inside docker image
      when: result.exists == False
      shell: chown -R "{{ eth1_user_id }}" "{{ eth1_node_dir }}"
      become: true

    - name: Start Eth1 container
      when: result.exists == False
      docker_container:
        name: "{{ eth1_container_name }}"
        state: started
        image: "{{ eth1_image_name }}"
        pull: true
        restart_policy: unless-stopped
        memory_swappiness: 0
        kernel_memory: "{{eth1_kernel_memory}}"
        network_mode: host
        restart: "{{ eth1_require_restart | default(false) }}"
        log_options: "{{ common_log_options }}"
        log_driver: "{{ common_log_driver }}"
        volumes: "{{eth1_volumes}}"
        memory: "{{eth1_memory}}"
        memory_swap: "{{eth1_memory}}"
        command: "{{ eth1_start_args }}"
        env: "{{ eth1_env | default({}) }}"
        user: "{{ eth1_user_id }}"
