- name: Start thanos
  hosts: "global_federation"
  gather_facts: true
  serial: 20
  tasks:
    - name: Creates thanos data dir
      file:
        path: "{{thanos_data_dir}}"
        state: directory

    - name: Creates thanos conf dir
      file:
        path: "{{thanos_conf_dir}}"
        state: directory

    - name: Archive local_thanos_conf_dir dir to prepare for upload
      archive:
        path: "{{local_thanos_conf_dir}}/*"
        dest: "{{local_thanos_conf_archive}}"
      delegate_to: localhost

    - name: Upload thanos conf to remote
      unarchive:
        src: "{{ local_thanos_conf_archive }}"
        dest: "{{ thanos_conf_dir }}"
        
    - name: Modify permissions to match user-group inside docker image
      shell: chown -R "{{ ansible_user }}" "{{ thanos_data_dir }}" && chown -R "{{ ansible_user }}" "{{ thanos_conf_dir }}"
      become: true

    - name: Create thanos docker network
      docker_network:
        name: thanos

    - name: Start minio s3 test container
      docker_container:
        name: "minio"
        state: started
        image: "minio/minio:latest"
        pull: true
        ports:
          - "19001:9001"
        restart_policy: unless-stopped
        network_mode: thanos
        entrypoint: "sh"
        command: "-c 'mkdir -p /data/thanos && minio server /data --console-address :9001'"
        env:
          MINIO_ROOT_USER: EXAMPLEKEY
          MINIO_ROOT_PASSWORD: EXAMPLESECRET

    - name: Start thanos store container
      docker_container:
        name: "{{ thanos_store_container_name }}"
        state: started
        image: "{{ thanos_image_name }}"
        pull: true
        restart_policy: unless-stopped
        memory_swappiness: 0
        kernel_memory: "{{thanos_kernel_memory}}"
        network_mode: thanos
        restart: "{{ thanos_require_restart | default(false) }}"
        log_options: "{{ common_log_options }}"
        log_driver: "{{ common_log_driver }}"
        volumes: "{{thanos_volumes}}"
        memory: "{{thanos_memory}}"
        memory_swap: "{{thanos_memory}}"
        command: "{{ thanos_store_start_args }}"
        env: "{{ thanos_env | default({}) }}"
        user: "{{ thanos_user_id }}"

    - name: Start thanos sidecar container
      docker_container:
        name: "{{ thanos_sidecar_container_name }}"
        state: started
        image: "{{ thanos_image_name }}"
        pull: true
        restart_policy: unless-stopped
        memory_swappiness: 0
        kernel_memory: "{{thanos_kernel_memory}}"
        etc_hosts: "{{ thanos_etc_hosts }}"
        network_mode: thanos
        restart: "{{ thanos_require_restart | default(false) }}"
        log_options: "{{ common_log_options }}"
        log_driver: "{{ common_log_driver }}"
        volumes: "{{thanos_volumes}}"
        memory: "{{thanos_memory}}"
        memory_swap: "{{thanos_memory}}"
        command: "{{ thanos_sidecar_start_args }}"
        env: "{{ thanos_env | default({}) }}"
        user: "{{ thanos_user_id }}"

    - name: Start thanos receive container
      docker_container:
        name: "{{ thanos_receive_container_name }}"
        state: started
        image: "{{ thanos_image_name }}"
        pull: true
        ports:
          - "10903:10903"
        restart_policy: unless-stopped
        memory_swappiness: 0
        kernel_memory: "{{thanos_kernel_memory}}"
        network_mode: thanos
        restart: "{{ thanos_require_restart | default(false) }}"
        log_options: "{{ common_log_options }}"
        log_driver: "{{ common_log_driver }}"
        volumes: "{{thanos_volumes}}"
        memory: "{{thanos_memory}}"
        memory_swap: "{{thanos_memory}}"
        command: "{{ thanos_receive_start_args }}"
        env: "{{ thanos_env | default({}) }}"
        user: "{{ thanos_user_id }}"

    - name: Start thanos compact container
      docker_container:
        name: "{{ thanos_compact_container_name }}"
        state: started
        image: "{{ thanos_image_name }}"
        pull: true
        restart_policy: unless-stopped
        memory_swappiness: 0
        kernel_memory: "{{thanos_kernel_memory}}"
        network_mode: thanos
        restart: "{{ thanos_require_restart | default(false) }}"
        log_options: "{{ common_log_options }}"
        log_driver: "{{ common_log_driver }}"
        volumes: "{{thanos_volumes}}"
        memory: "{{thanos_memory}}"
        memory_swap: "{{thanos_memory}}"
        command: "{{ thanos_compact_start_args }}"
        env: "{{ thanos_env | default({}) }}"
        user: "{{ thanos_user_id }}"

    - name: Start thanos query container
      docker_container:
        name: "{{ thanos_query_container_name }}"
        state: started
        image: "{{ thanos_image_name }}"
        pull: true
        ports:
          - "10902:10902"
        restart_policy: unless-stopped
        memory_swappiness: 0
        kernel_memory: "{{thanos_kernel_memory}}"
        network_mode: thanos
        restart: "{{ thanos_require_restart | default(false) }}"
        log_options: "{{ common_log_options }}"
        log_driver: "{{ common_log_driver }}"
        volumes: "{{thanos_volumes}}"
        memory: "{{thanos_memory}}"
        memory_swap: "{{thanos_memory}}"
        command: "{{ thanos_query_start_args }}"
        env: "{{ thanos_env | default({}) }}"
        user: "{{ thanos_user_id }}"
