---
- name: Register beacon metrics to prometheus
  copy:
    dest: "{{ prometheus_file_sd_dir }}/beacon.yml"
    content: |
      - labels:
          appname: beacon
          testnet: {{ TESTS[runningTest][0] }}
        targets:
        - {{ beacon_container_name }}:{{ beacon_metrics_port }}
