- name: Start promtail
  hosts: "{{ variable_host }}"
  gather_facts: false
  tasks:
    - name: Creates promtail config dir
      file:
        path: "{{ promtail_config_dir }}"
        state: directory

    - name: Copy promtail conf to remote
      copy:
        src: "{{ local_promtail_conf_dir }}/"
        dest: "{{ promtail_config_dir }}"

    - name: Replace promtail_loki_url variable in conf file
      replace:
        path: "{{ promtail_config_dir }}/config.yml"
        regexp: '##promtail_loki_url##'
        replace: '{{promtail_loki_url}}'

    - name: Replace variable in conf file
      replace:
        path: "{{ promtail_config_dir }}/config.yml"
        regexp: "##inventory_hostname##"
        replace: "{{ inventory_hostname }}"

    - name: Enable receiver get docker logs
      blockinfile:
        path: "{{ promtail_config_dir }}/config.yml"
        block: |
          - job_name: {{ inventory_hostname }}_push
            loki_push_api:
              server:
                http_listen_port: 3500
                grpc_listen_port: 3600
              labels:
                pushserver: {{ inventory_hostname }}_push

    - name: Modify permissions to match user-group inside docker image
      shell: chown -R "{{ ansible_user }}" "{{ promtail_config_dir }}"
      become: true

    - name: Start promtail container
      docker_container:
        name: "{{ promtail_container_name }}"
        state: started
        image: "{{ promtail_image_name }}"
        pull: true
        restart_policy: unless-stopped
        memory_swappiness: 0
        kernel_memory: "{{promtail_kernel_memory}}"
        network_mode: host
        restart: "{{ promtail_require_restart | default(false) }}"
        log_options: "{{ json_log_options }}"
        log_driver: "{{ json_log_driver }}"
        volumes: "{{promtail_volumes}}"
        memory: "{{promtail_memory}}"
        memory_swap: "{{promtail_memory}}"
        command: "{{ promtail_start_args }}"
        env: "{{ promtail_env | default({}) }}"
        user: "{{ promtail_user_id }}"

    - name: Register promtail metrics to prometheus
      copy:
        dest: "{{ prometheus_file_sd_dir }}/promtail.yml"
        content: |
          - labels:
              instance: promtail
            targets:
            - localhost:9080
