---
- name: Include ENR groups
  include_vars: "{{enr_groups_file}}"

- name: Set bootnodes_enr to the group enr
  set_fact:
    bootnode_enrs: ["{{ lookup('vars', hostvars[inventory_hostname].rw_host + '_enr') }}"]

- name: Creates beacon dir
  file:
    path: "{{beacon_node_dir}}"
    state: directory
    
- name: Modify permissions to match user-group inside docker image
  shell: chown -R "{{ beacon_user_id }}" "{{ beacon_node_dir }}"
  become: true

- name: Start Eth2 beacon node container EXPOSED TO INTERNET DEBUG ENDPOINT
  docker_container:
    name: "{{ beacon_container_name }}"
    state: started
    image: "{{ beacon_image_name }}"
    pull: true
    ports:
      - "{{public_ip_address}}:{{beacon_api_port}}:{{beacon_api_port}}"
      - "{{public_ip_address}}:{{beacon_p2p_port}}:{{beacon_p2p_port}}"
      - "{{public_ip_address}}:{{beacon_p2p_port}}:{{beacon_p2p_port}}/udp"
    restart_policy: unless-stopped
    memory_swappiness: 0
    network_mode: "{{ docker_monitoring_network }}"
    restart: "{{ restart_container_if_exists | default(false) }}"
    log_options: "{{ common_log_options }}"
    log_driver: "{{ common_log_driver }}"
    volumes: "{{beacon_volumes}}"
    memory: "{{beacon_memory}}"
    memory_swap: "{{beacon_memory}}"
    command: "{{ beacon_start_args }}"
    env: "{{ beacon_env | default({}) }}"
    user: "{{ beacon_user_id }}"
    labels: "{{ testnet_labels }}"
  when: enable_debug_public | default(false) == true

- name: Start Eth2 beacon node container NOT EXPOSED TO INTERNET DEBUG ENDPOINT
  docker_container:
    name: "{{ beacon_container_name }}"
    state: started
    image: "{{ beacon_image_name }}"
    pull: true
    ports:
      - "{{public_ip_address}}:{{beacon_p2p_port}}:{{beacon_p2p_port}}"
      - "{{public_ip_address}}:{{beacon_p2p_port}}:{{beacon_p2p_port}}/udp"
    restart_policy: unless-stopped
    memory_swappiness: 0
    network_mode: "{{ docker_monitoring_network }}"
    restart: "{{ restart_container_if_exists | default(false) }}"
    log_options: "{{ common_log_options }}"
    log_driver: "{{ common_log_driver }}"
    volumes: "{{beacon_volumes}}"
    memory: "{{beacon_memory}}"
    memory_swap: "{{beacon_memory}}"
    command: "{{ beacon_start_args }}"
    env: "{{ beacon_env | default({}) }}"
    user: "{{ beacon_user_id }}"
    labels: "{{ testnet_labels }}"
  when: enable_debug_public | default(false) == false
