---
- name: Register validator metrics to prometheus
  when: eth2_client_name == 'lighthouse' or eth2_client_name == 'prysm'
  copy:
    dest: "{{ prometheus_file_sd_dir }}/validator.yml"
    content: |
      - labels:
          appname: validator
          testnet: {{ TESTS[runningTest][0] }}
        targets:
        - {{ validator_container_name }}:{{ validator_metrics_port }}
