---
- name: Include geth variables
  include_vars: "{{inventory_dir}}/group_vars/eth1client_geth.yml"

- name: Creates eth1 data dir
  file:
    path: "{{eth1_node_dir}}"
    state: directory

- name: Modify permissions to match user-group inside docker image
  shell: chown -R "{{ eth1_user_id }}" "{{ eth1_node_dir }}"
  become: true

- name: Creates eth1 beacondata dir
  file:
    path: "{{eth1_beacondata_dir}}"
    state: directory

- name: Modify permissions to match user-group inside docker image
  shell: chown -R "{{ eth1_user_id }}" "{{ eth1_beacondata_dir }}"
  become: true

- name: Copy jwt secret
  copy:
    src: "{{local_premerge_custom_config_data_host_dir}}/jwtsecret"
    dest: "{{ jwtsecret_file_outside }}"

- name: Start Eth1 container
  docker_container:
    name: "{{ eth1_container_name }}"
    state: started
    image: "{{ eth1_image_name }}"
    pull: true
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "{{eth1_auth_rpc_port}}:{{eth1_auth_rpc_port}}"
      - "{{eth1_rpc_port}}:{{eth1_rpc_port}}"
      - "{{eth1_ws_rpc_port}}:{{eth1_ws_rpc_port}}"
    restart_policy: unless-stopped
    memory_swappiness: 0
    network_mode: "{{docker_monitoring_network}}"
    restart: "{{ restart_container_if_exists | default(false) }}"
    log_options: "{{ common_log_options }}"
    log_driver: "{{ common_log_driver }}"
    volumes: "{{eth1_volumes}}"
    memory: "{{eth1_memory}}"
    memory_swap: "{{eth1_memory}}"
    command: "{{ eth1_start_args }}"
    env: "{{ eth1_env | default({}) }}"
    user: "{{ eth1_user_id }}"

- name: Register geth metrics to prometheus
  copy:
    dest: "{{ prometheus_file_sd_dir }}/geth.yml"
    content: |
      - labels:
          appname: {{ eth1_container_name }}
        targets:
        - {{ eth1_container_name }}:{{eth1_metrics_port}}
  when: eth1_metrics_port | default('') != ''

- name: Start Eth2 beacon node container
  docker_container:
    name: "{{ beacon_container_name }}"
    state: started
    image: "{{ beacon_image_name }}"
    pull: true
    ports:
      - "{{beacon_p2p_port}}:{{beacon_p2p_port}}"
      - "{{beacon_p2p_port}}:{{beacon_p2p_port}}/udp"
    restart_policy: unless-stopped
    memory_swappiness: 0
    network_mode: "{{docker_monitoring_network}}"
    restart: "{{ restart_container_if_exists | default(false) }}"
    log_options: "{{ common_log_options }}"
    log_driver: "{{ common_log_driver }}"
    volumes: "{{beacon_volumes}}"
    memory: "{{beacon_memory}}"
    memory_swap: "{{beacon_memory}}"
    command: "{{ beacon_start_args }}"
    env: "{{ beacon_env | default({}) }}"
    user: "{{ beacon_user_id }}"

- name: Register beacon metrics to prometheus
  copy:
    dest: "{{ prometheus_file_sd_dir }}/beacon.yml"
    content: |
      - labels:
          appname: beacon-geth
        targets:
        - {{ beacon_container_name }}:{{ beacon_metrics_port }}
