- name: Start loki
  hosts: "{{ variable_host }}"
  gather_facts: false
  tasks:
    - name: Creates loki config dir
      file:
        path: "{{ loki_config_dir }}"
        state: directory

    - name: Copy loki conf to remote
      copy:
        src: "{{ local_loki_conf_dir }}/"
        dest: "{{ loki_config_dir }}"

    - name: Modify permissions to match user-group inside docker image
      shell: chown -R "{{ ansible_user }}" "{{ loki_config_dir }}"
      become: true

    - name: Start loki container
      docker_container:
        name: "{{ loki_container_name }}"
        state: started
        image: "{{ loki_image_name }}"
        pull: true
        restart_policy: unless-stopped
        memory_swappiness: 0
        kernel_memory: "{{loki_kernel_memory}}"
        etc_hosts: "{{ docker_etc_hosts }}"
        network_mode: host
        restart: "{{ loki_require_restart | default(false) }}"
        log_options: "{{ json_log_options }}"
        log_driver: "{{ json_log_driver }}"
        volumes: "{{loki_volumes}}"
        command: "{{ loki_start_args }}"
        memory: "{{loki_memory}}"
        memory_swap: "{{loki_memory}}"
        env: "{{ loki_env | default({}) }}"
        user: "{{ loki_user_id }}"

    - name: Register loki metrics to prometheus
      copy:
        dest: "{{ prometheus_file_sd_dir }}/loki.yml"
        content: |
          - labels:
              instance: loki
            targets:
            - localhost:3100
