---
- name: Creates test data dir
  file:
    path: "{{data_dir}}/{{test.key}}"
    state: directory

- name: Copy config file
  copy:
    src: "{{ running_dir }}/config.yaml"
    dest: "{{ data_dir }}/{{test.key}}"

- name: Replace variable in conf file
  replace:
    path: "{{ data_dir }}/{{test.key}}/config.yaml"
    regexp: "{{item.0}}"
    replace: "{{item.1}}"
  loop:
    - ["##CONFIG_NAME##", "{{test.value[0]}}"]
    - ["##MIN_GENESIS_ACTIVE_VALIDATOR_COUNT##", "{{groups[test.key + '_validator']|length * VALIDATORS_PER_INSTANCE}}"]
    - ["##DATE_FULL##", "{{DATE_FULL.stdout}}"]
    - ["##MIN_GENESIS_TIME##", "{{MIN_GENESIS_TIME}}"]
    - ["##GENESIS_DELAY##", "{{GENESIS_DELAY}}"]
    - ["##SECONDS_PER_SLOT##", "{{test.value[1]}}"]
    - ["##NETWORK##", "{{NETWORK}}"]
    - ["##DEPOSIT_CHAIN_ID##", "{{DEPOSIT_CHAIN_ID}}"]
    - ["##DEPOSIT_NETWORK_ID##", "{{DEPOSIT_NETWORK_ID}}"]
    - ["##DEPOSIT_CONTRACT_ADDRESS##", "{{transaction_hash_details.contract_address}}"]

- name: Create deploy_block.txt
  copy:
    dest: "{{ data_dir }}/{{test.key}}/deploy_block.txt"
    content: |
      {{transaction_hash_details.block_number}}

- name: Create deposit_contract.txt
  copy:
    dest: "{{ data_dir }}/{{test.key}}/deposit_contract.txt"
    content: |
      {{transaction_hash_details.contract_address}}

- name: Create empty mnemonics.yaml
  copy:
    dest: "{{ data_dir }}/{{test.key}}/mnemonics.yaml"
    content: ""

- name: Create empty secret_mnemonics.yaml
  copy:
    dest: "{{ data_dir }}/{{test.key}}/secret_mnemonics.yaml"
    content: ""

- name: Generate mnenomic and add to file
  include_tasks: tasks/generate_mnemonics.yml
  loop: "{{groups[test.key + '_validator']}}"

- name: Generate genesis state
  shell: "docker run --user $(id -u):$(id -u) --network host --rm -v {{data_dir}}/{{test.key}}:/data gathecageorge/eth2-test-genesis:latest phase0 --config /data/config.yaml --eth1-block {{transaction_hash_details.block_hash}} --mnemonics /data/mnemonics.yaml --timestamp {{MIN_GENESIS_TIME - GENESIS_DELAY}} --tranches-dir /data/tranches --state-output /data/genesis.ssz"
