---
- name: Remove testnet directory
  become: true
  file:
    path: "{{testnet_dir}}"
    state: absent

- name: Recreate testnet dir
  file:
    path: "{{testnet_dir}}"
    state: directory

- name: Archive custom_config_data dir to prepare for upload
  archive:
    path: "{{local_custom_config_data_host_dir}}/{{runningTest}}/*"
    dest: "{{local_custom_config_data_host_archive}}"
  throttle: 1
  run_once: true
  delegate_to: localhost

- name: Upload config data to remote
  unarchive:
    src: "{{ local_custom_config_data_host_archive }}"
    dest: "{{ testnet_dir }}/"

- name: Remove {{local_custom_config_data_host_archive}} archive after upload
  file:
    path: "{{ local_custom_config_data_host_archive }}"
    state: absent
  throttle: 1
  run_once: true
  delegate_to: localhost
    