---
- name: Archive custom_config_data dir to prepare for upload PREMERGE
  when: TESTS[runningTest][3] == 'premerge'
  archive:
    path: "{{local_custom_config_data_host_dir}}/{{runningTest}}/*"
    dest: "{{local_custom_config_data_host_archive}}"
  throttle: 1
  run_once: true
  delegate_to: localhost

- name: Archive custom_config_data dir to prepare for upload POSTMERGE
  when: TESTS[runningTest][3] == 'postmerge'
  archive:
    path: "{{local_custom_config_data_host_dir}}/{{runningTest}}/data/custom_config_data/*"
    dest: "{{local_custom_config_data_host_archive}}"
  throttle: 1
  run_once: true
  delegate_to: localhost

- name: Upload config data to globalfederation1 so all other servers can get it from there instead of multiple upload
  copy:
    src: "{{ local_custom_config_data_host_archive }}"
    dest: "{{ home_dir }}/tmp/{{ custom_config_data_host_archive_filename }}"
  throttle: 1
  run_once: true
  delegate_to: globalfederation1

- name: uploads custom chain config and genesis data if needed, create jwtsecrets required
  shell: |
    # Remove beacon container &&  beacon data if present && unregister metrics
    sudo rm -f {{ prometheus_file_sd_dir }}/beacon.yml
    docker rm -f {{beacon_container_name}} || true
    sudo rm -rf {{beacon_node_dir}}

    # Recreate testnet config and upload custom_config_data
    sudo rm -rf {{testnet_dir}}
    mkdir {{testnet_dir}}
    curl -O http://{{ hostvars['globalfederation1']['public_ip_address'] }}:1111/{{ custom_config_data_host_archive_filename }}
    tar -xvf {{ custom_config_data_host_archive_filename }} -C {{ testnet_dir }}
    rm {{ custom_config_data_host_archive_filename }}

    # Copy CL jwtsecret file
    cat > {{ testnet_dir }}/jwtsecret << EOF
    {{JWTSECRET}}
    EOF

    # Copy EL jwtsecret file POSTMERGE
    if [ '{{ TESTS[runningTest][3] }}' = 'postmerge' ]; then
    cat > {{ testnet_dir }}/el_jwtsecret << EOF
    {{JWTSECRET}}
    EOF
    fi

- name: Remove config from globalfederation1
  file:
    path: "{{ home_dir }}/tmp/{{ custom_config_data_host_archive_filename }}"
    state: absent
  throttle: 1
  run_once: true
  delegate_to: globalfederation1

- name: Remove {{local_custom_config_data_host_archive}} archive after upload
  file:
    path: "{{ local_custom_config_data_host_archive }}"
    state: absent
  throttle: 1
  run_once: true
  delegate_to: localhost
