bootnode_container_name: bootnode
bootnode_memory: 2000m
bootnode_image_name: protolambda/eth2-bootnode:cleanup

bootnode_host_dir: "{{home_dir}}/bootnode_data"

bootnode_port: 9001
bootnode_api_port: 8002

bootnode_ip: "{{ansible_host}}"

# 32 bytes, hex encoded, no 0x.
# To generate one run `head -c 32 /dev/urandom|xxd -ps -c 32` Generated automatically when ran using playbook
bootnode_p2p_priv_key: ""

bootnode_start_args: >
  {% if (bootnode_enrs is defined) and bootnode_enrs %}
  --bootnodes="{{ bootnode_enrs | join(',') }}"
  {% endif %}
  --color=false
  --enr-ip="{{bootnode_ip}}"
  --enr-udp="{{bootnode_port}}"
  --level=error
  --listen-ip=0.0.0.0
  --listen-udp="{{bootnode_port}}"
  --api-addr="0.0.0.0:{{bootnode_api_port}}"
  --node-db="/data/localnode.db"
  --priv="{{bootnode_p2p_priv_key}}"