##############################################
# image name and image location
##############################################
eth1_client_name: geth
eth1_image_name: ethereum/client-go:stable
eth1_container_name: eth1_geth

##############################################
# volume mappings on remote host
##############################################
eth1_data_dir: "/var/lib/goethereum"
eth1_volumes:
  - "{{eth1_node_dir}}:{{eth1_data_dir}}"

#Logging verbosity: 0-6 (0=silent, 1=error, 2=warn, 3=info, 4=core, 5=debug, 6=debug detail)
##############################################
# arguments to run the containers with
##############################################
jwtsecret_file_inside: "{{eth1_data_dir}}/geth/jwtsecret_new"
jwtsecret_file_outside: "{{eth1_node_dir}}/geth/jwtsecret_new"
eth1_start_args: >
   --{{ NETWORK }} 
   --datadir {{eth1_data_dir}}
   --http --http.api "admin,engine,net,eth,consensus" 
   --http.port {{ eth1_rpc_port }} 
   --http.addr 0.0.0.0 
   --http.corsdomain "*" 
   --ws --ws.api "engine,net,eth,consensus" 
   --ws.port {{ eth1_ws_rpc_port }} 
   --ws.addr 0.0.0.0
   --authrpc.port={{ eth1_auth_rpc_port }}
   --authrpc.addr=0.0.0.0
   --authrpc.vhosts=*
   --authrpc.jwtsecret={{jwtsecret_file_inside}}
   --nat extip:{{ public_ip_address }}
   --allow-insecure-unlock
   --metrics
   --pprof
   --pprof.addr 0.0.0.0
   --pprof.port={{ eth1_pprof_port }}
   --vmodule=rpc=5
   --maxpeers=75

##############################################
# memory limits
##############################################
eth1_memory: 5000M

##############################################
# file permissions and user ids
##############################################
eth1_user_id: "1000:1000"
