##############################################
# image name and image location
##############################################
eth1_image_name: ethereum/client-go:stable

##############################################
# volume mappings on remote host
##############################################
eth1_volumes:
  - "{{eth1_node_dir}}:/.ethereum"

##############################################
# arguments to run the containers with
##############################################
eth1_start_args: >
   --{{ eth1_network }} 
   --http --http.api "engine,net,eth,consensus" 
   --http.port {{ eth1_rpc_port }} 
   --http.addr 0.0.0.0 
   --http.corsdomain "*" 
   --ws 
   --ws.api "net,eth,consensus,engine" 
   --ws.port {{ eth1_ws_rpc_port }} 

##############################################
# memory limits
##############################################
eth1_memory: 5000M
eth1_kernel_memory: 5500M

##############################################
# file permissions and user ids
##############################################
eth1_user_id: "1000:1000"
