eth1_client_name: besu
eth1_image_name: hyperledger/besu:latest
eth1_container_name: eth1_besu

eth1_memory: 5000M

eth1_volumes:
  - "{{eth1_node_dir}}:/eth1data"

eth1_start_args: >
  --data-path="/eth1data"
  --network={{NETWORK}}
  --rpc-http-enabled=true
  --rpc-http-host={{public_ip_address}}
  --rpc-http-port={{eth1_rpc_port}}
  --rpc-http-cors-origins="*"
  --rpc-ws-enabled=true
  --rpc-ws-host={{public_ip_address}}
  --rpc-ws-port={{eth1_ws_rpc_port}}
  --host-allowlist="*"
  --p2p-enabled=true

eth1_user_id: "1000:1000"
