##############################################
# image name and image location
##############################################
eth1_client_name: geth
eth1_image_name: parithoshj/geth:merge-f72c361
eth1_container_name: eth1_geth

##############################################
# volume mappings on remote host
##############################################
eth1_data_dir: "/var/lib/goethereum"
eth1_volumes:
  - "{{eth1_node_dir}}:{{eth1_data_dir}}"

#Logging verbosity: 0-6 (0=silent, 1=error, 2=warn, 3=info, 4=core, 5=debug, 6=debug detail)
##############################################
# arguments to run the containers with
##############################################
eth1_start_args: >
   --datadir {{eth1_data_dir}}
   --networkid={{chainID}} --catalyst
   --metrics
   --http --http.api "engine,net,eth" 
   --http.port {{ eth1_rpc_port }} 
   --http.addr 0.0.0.0 
   --http.corsdomain "*" 
   --ws --ws.api "engine,net,eth" 
   --ws.port {{ eth1_ws_rpc_port }} 
   --ws.addr 0.0.0.0
   --nat extip:{{ansible_host}}
   --allow-insecure-unlock
   --verbosity 2
   --maxpeers=200
   --ethstats={{inventory_hostname}}:KintsugiNetwork@ethstats.kintsugi.themerge.dev
   {% if (eth1_bootnode_enode is defined) and eth1_bootnode_enode %}
   --bootnodes "{{ eth1_bootnode_enode | join(',') }}"
   {% endif %}

##############################################
# memory limits
##############################################
eth1_memory: 5000M
eth1_kernel_memory: 5500M

##############################################
# file permissions and user ids
##############################################
eth1_user_id: "1000:1000"
