##############################################
# execution client
##############################################
eth1_client_name: geth
eth1_image_name: ethereum/client-go:stable
eth1_container_name: geth
eth1_data_dir: "/var/lib/goethereum"
eth1_volumes:
  - "{{eth1_node_dir}}:{{eth1_data_dir}}"
  - "{{jwtsecret_file_outside}}:/jwtsecret"
eth1_memory: 2500M
eth1_user_id: "1000:1000"
eth1_start_args: >
   --{{ NETWORK }} 
   --verbosity 1
   --datadir {{eth1_data_dir}}
   --http --http.api "admin,engine,net,eth" 
   --http.port {{ eth1_rpc_port }} 
   --http.addr 0.0.0.0 
   --http.vhosts=*
   --http.corsdomain "*" 
   --ws --ws.api "engine,net,eth" 
   --ws.port {{ eth1_ws_rpc_port }} 
   --ws.addr 0.0.0.0
   --authrpc.port={{ eth1_auth_rpc_port }}
   --authrpc.addr=0.0.0.0
   --authrpc.vhosts=*
   --authrpc.jwtsecret=/jwtsecret
   --nat extip:{{ public_ip_address }}
   --allow-insecure-unlock
   --metrics
   --pprof
   --pprof.addr 0.0.0.0
   --pprof.port={{ eth1_pprof_port }}
   --vmodule=rpc=5
   --maxpeers=75

##############################################
# consensus client
##############################################
eth2_client_name: lighthouse
beacon_container_name: beacon
beacon_image_name: sigp/lighthouse:latest
beacon_volumes:
  - "{{eth1_beacondata_dir}}:/beacondata"
  - "{{jwtsecret_file_outside}}:/jwtsecret"
beacon_memory: 2500M
beacon_user_id: "1000:1000"
beacon_start_args: >
  lighthouse
  --debug-level="info"
  --network {{ NETWORK }} 
  bn
  --datadir "/beacondata"
  --disable-enr-auto-update
  --enr-address={{public_ip_address}}
  --enr-tcp-port={{beacon_p2p_port}} --enr-udp-port={{beacon_p2p_port}}
  --port={{beacon_p2p_port}} --discovery-port={{beacon_p2p_port}}
  --eth1 --execution-endpoints http://{{eth1_container_name}}:8551
  {% if (bootnode_enrs is defined) and bootnode_enrs %}
  --boot-nodes="{{ bootnode_enrs | join(',') }}"
  {% endif %}  
  --http --http-allow-sync-stalled
  --http-address 0.0.0.0
  --http-port "{{beacon_api_port}}"
  --metrics
  --metrics-address 0.0.0.0
  --metrics-port "{{beacon_metrics_port}}"
  --listen-address 0.0.0.0
  --graffiti="{{graffiti}}"
  --target-peers={{hi_peer_count}}
  --jwt-secrets="/jwtsecret"
  --suggested-fee-recipient={{ETH1_FROM_ADDR}}
  --checkpoint-sync-url={{CL_CHECKPOINT_SYNC}}

# eth2_client_name: teku
# beacon_container_name: beacon
# beacon_image_name: consensys/teku:latest
# beacon_volumes:
#   - "{{eth1_beacondata_dir}}:/beacondata"
#   - "{{jwtsecret_file_outside}}:/jwtsecret"
# beacon_memory: 2500M
# beacon_user_id: "1000:1000"
# beacon_start_args: >
#   --network {{ NETWORK }} 
#   --initial-state "{{CL_CHECKPOINT_SYNC_TEKU}}"
#   --data-path "/beacondata"
#   --data-storage-mode=PRUNE
#   --p2p-enabled=true
#   --p2p-advertised-ip={{public_ip_address}}
#   --p2p-port="{{beacon_p2p_port}}"
#   --p2p-advertised-port={{beacon_p2p_port}}
#   --logging="{{ beacon_log_level | default('debug') }}"
#   --log-destination=CONSOLE
#   --log-file="/beacondata/log_outputs"
#   --p2p-peer-upper-bound={{hi_peer_count}}
#   {% if (bootnode_enrs is defined) and bootnode_enrs %}
#   --p2p-discovery-bootnodes="{{ bootnode_enrs | join(',') }}"
#   {% endif %}
#   --metrics-enabled=true --metrics-interface=0.0.0.0 --metrics-port="{{beacon_metrics_port}}"
#   --p2p-discovery-enabled=true
#   --p2p-peer-lower-bound=1
#   --rest-api-enabled=true
#   --rest-api-docs-enabled=true
#   --rest-api-interface=0.0.0.0
#   --rest-api-port="{{beacon_api_port}}"
#   --metrics-host-allowlist="*"
#   --rest-api-host-allowlist="*"
#   --ee-endpoint="http://{{eth1_container_name}}:8551"
#   --eth1-endpoint "http://{{eth1_container_name}}:8551"
#   --ee-jwt-secret-file=/jwtsecret
#   --validators-proposer-default-fee-recipient={{ETH1_FROM_ADDR}}
