##############################################
# image name and image location
##############################################
eth2_client_name: nimbus

#todo check latest
beacon_image_name: 'statusim/nimbus-eth2:multiarch-latest'
#beacon_image_name: "{{ 'statusim/nimbus-eth2:multiarch-latest' if TESTS[runningTest][1] == 12 else '%s%d'|format('gathecageorge/nimbus-eth2:slot', TESTS[runningTest][1]) }}"
validator_image_name: "{{ beacon_image_name }}"

##############################################
# volume mappings on remote host
##############################################
beacon_volumes:
  - "{{beacon_node_dir}}:/beacondata"
  - "{{testnet_dir}}:/custom_config_data"
  - "{{validator_node_dir}}:/validatordata"

##############################################
# arguments to run the containers with
##############################################
beacon_start_args: >
  --data-dir="/beacondata"
  --non-interactive
  --status-bar=false
  --tcp-port={{beacon_p2p_port}}
  --udp-port={{beacon_p2p_port}}
  --max-peers="{{hi_peer_count}}"
  --network="/custom_config_data"
  {% if (bootnode_enrs is defined) and bootnode_enrs %}
  --bootstrap-node="{{ bootnode_enrs | join(',') }}"
  {% endif %}
  --graffiti="{{graffiti}}"
  --log-level="{{ beacon_log_level | default('debug') }}"
  --rest --rest-port={{beacon_api_port}} --rest-address=0.0.0.0
  --enr-auto-update=false
  --doppelganger-detection=off
  --metrics --metrics-port={{beacon_metrics_port}} --metrics-address=0.0.0.0
  --listen-address=0.0.0.0
  --nat="extip:{{ansible_host}}"
  --validators-dir="/validatordata/keys"
  --secrets-dir="/validatordata/secrets"
  --validator-monitor-auto
  --dump:on
  {% if (use_premerge_network) %}
  --web3-url="{{eth1endpoint_premerge}}"
  --terminal-total-difficulty-override={{merge_terminal_total_difficulty}}
  {% else %}
  --web3-url="{{eth1endpoint}}"
  --jwt-secret=/custom_config_data/jwtsecret
  {% endif %}

##############################################
# memory limits
##############################################
validator_memory: 2000M
beacon_memory: 5000M

##############################################
# file permissions and user ids
##############################################
keystores_file_mode: "0700"
beacon_user_id: "1000:100"
validator_user_id: "1000:100"

# Nimbus currently runs on a combined beacon validator process, future versions will work as separate processes
separate_validator_process_enabled: false