##############################################
# image name and image location
##############################################
eth2_client_name: lighthouse
beacon_image_name: sigp/lighthouse:v1.5.1
validator_image_name: sigp/lighthouse:v1.5.1
beacon_endpoint: "http://127.0.0.1:{{beacon_api_port}}"

##############################################
# volume mappings on remote host
##############################################
beacon_volumes:
  - "{{beacon_node_dir}}:/beacondata"
  - "{{testnet_dir}}:/custom_config_data"
  - "{{testnet_dir}}/eth2_config.yaml:/custom_config_data/config.yaml"

validator_volumes:
  - "{{validator_node_dir}}:/validatordata"
  - "{{testnet_dir}}:/custom_config_data"
  - "{{testnet_dir}}/eth2_config.yaml:/custom_config_data/config.yaml"

##############################################
# arguments to run the containers with
##############################################
beacon_start_args: >
  lighthouse
  --debug-level="{{ beacon_log_level | lower }}"
  --datadir "/beacondata"
  --testnet-dir="/custom_config_data"
  bn
  --disable-enr-auto-update
  --enr-address={{public_ip_address}}
  --enr-tcp-port={{beacon_p2p_port}} --enr-udp-port={{beacon_p2p_port}}
  --port={{beacon_p2p_port}} --discovery-port={{beacon_p2p_port}}
  --eth1 --eth1-endpoints "{{eth1endpoint}}"
  {% if (bootnode_enrs is defined) and bootnode_enrs %}
  --boot-nodes="{{ bootnode_enrs | join(',') }}"
  {% endif %}  --http
  --http-address 0.0.0.0
  --http-port "{{beacon_api_port}}"
  --metrics
  --metrics-address 0.0.0.0
  --metrics-port "{{beacon_metrics_port}}"
  --listen-address 0.0.0.0
  --graffiti="{{graffiti}}"
  --target-peers={{hi_peer_count}}

validator_start_args: >
  lighthouse
  --testnet-dir="/custom_config_data"
  vc
  --validators-dir="/validatordata/validators"
  --secrets-dir="/validatordata/secrets"
  --init-slashing-protection
  --server={{beacon_endpoint}}
  --graffiti="{{graffiti}}"
  --http --http-port={{validator_rpc_port}}
##############################################
# memory limits
##############################################
validator_memory: 2000M
validator_kernel_memory: 2500M
beacon_memory: 5000M
beacon_kernel_memory: 5500M

##############################################
# file permissions and user ids
##############################################
keystores_file_mode: "0700"
beacon_user_id: "1000:1000"
validator_user_id: "1000:1000"