##############################################
# image name and image location
##############################################
eth2_client_name: teku

#todo check latest
beacon_image_name: consensys/teku:latest
validator_image_name: consensys/teku:latest
beacon_endpoint: "http://{{beacon_container_name}}:{{beacon_api_port}}"

##############################################
# volume mappings on remote host
##############################################
beacon_volumes:
  - "{{beacon_node_dir}}:/beacondata"
  - "{{testnet_dir}}:/custom_config_data"
  - "{{validator_node_dir}}:/validatordata"

validator_volumes:
  - "{{validator_node_dir}}:/validatordata"
  - "{{testnet_dir}}:/custom_config_data"

##############################################
# arguments to run the containers with
##############################################
beacon_start_args: >
  --network "/custom_config_data/config.yaml"
  --initial-state "/custom_config_data/genesis.ssz"
  --data-path "/beacondata"
  --data-storage-mode=PRUNE
  --p2p-enabled=true
  --p2p-advertised-ip={{public_ip_address}}
  --p2p-port="{{beacon_p2p_port}}"
  --p2p-advertised-port={{beacon_p2p_port}}
  --logging="{{ beacon_log_level | default('debug') }}"
  --log-destination=CONSOLE
  --log-file="/beacondata/log_outputs"
  --p2p-peer-upper-bound={{hi_peer_count}}
  {% if (bootnode_enrs is defined) and bootnode_enrs %}
  --p2p-discovery-bootnodes="{{ bootnode_enrs | join(',') }}"
  {% endif %}
  --metrics-enabled=true --metrics-interface=0.0.0.0 --metrics-port="{{beacon_metrics_port}}"
  --p2p-discovery-enabled=true
  --p2p-peer-lower-bound=1
  --rest-api-enabled=true
  --rest-api-docs-enabled=true
  --rest-api-interface=0.0.0.0
  --rest-api-port="{{beacon_api_port}}"
  --metrics-host-allowlist="*"
  --rest-api-host-allowlist="*"
  {% if (use_premerge_network) %}
  --ee-endpoint="{{eth1endpoint_premerge}}"
  --eth1-endpoint "{{eth1endpoint_premerge}}"
  {% else %}
  --ee-endpoint="{{eth1endpoint}}"
  --eth1-endpoint "{{eth1endpoint}}"
  --ee-jwt-secret-file=/custom_config_data/jwtsecret
  {% endif %}

validator_start_args: >
  validator-client 
  --network "/custom_config_data/config.yaml"
  --data-path "/validatordata"
  --validators-proposer-default-fee-recipient={{fee_recipient}}
  --beacon-node-api-endpoint "{{beacon_endpoint}}"
  --validators-graffiti="{{graffiti}}"
  --validator-keys "/validatordata/keys:/validatordata/secrets"

##############################################
# memory limits
##############################################
beacon_memory: 5000M
validator_memory: 2000M
beacon_env:
  JAVA_OPTS: "-XX:SoftMaxHeapSize=2g -Xmx4g"

# TODO: maybe configure logging style via env var later
#  LOG4J_CONFIGURATION_FILE: "/beacondata/log_config.xml"

##############################################
# file permissions and user ids
##############################################
keystores_file_mode: "0704"
beacon_user_id: "1000:1000"
validator_user_id: "1000:1000"
