##############################################
# image name and image location
##############################################
eth2_client_name: prysm

#todo check latest
beacon_image_name: prysmaticlabs/prysm-beacon-chain:latest
validator_image_name: prysmaticlabs/prysm-validator:latest

# GRPC, not REST JSON
beacon_endpoint: "{{beacon_container_name}}:{{beacon_grpc_port}}"

##############################################
# volume mappings on remote host
##############################################
beacon_volumes:
  - "{{beacon_node_dir}}:/beacondata"
  - "{{testnet_dir}}:/custom_config_data"

validator_volumes:
  - "{{testnet_dir}}:/custom_config_data"
  - "{{validator_node_dir}}:/validatordata"

##############################################
# arguments to run the containers with
##############################################
beacon_start_args: >
  --accept-terms-of-use=true
  --datadir="/beacondata"
  --genesis-state="/custom_config_data/genesis.ssz"
  --chain-config-file="/custom_config_data/config.yaml"
    {% if (bootnode_enrs is defined) and bootnode_enrs %}
    {% for bootnode_enrs in bootnode_enrs %}
    --bootstrap-node="{{ bootnode_enrs }}"
    {% endfor %}
    {% endif %}
  --verbosity="{{ beacon_log_level | default('debug') }}"
  --min-sync-peers=1
  --pprof
  --p2p-host-ip={{ansible_host}}
  --p2p-max-peers={{hi_peer_count}}
  --p2p-udp-port={{beacon_p2p_port}} --p2p-tcp-port={{beacon_p2p_port}}
  --monitoring-host=0.0.0.0 --monitoring-port={{beacon_metrics_port}}
  --rpc-host=0.0.0.0 --rpc-port={{beacon_grpc_port}}
  --grpc-gateway-host=0.0.0.0
  --grpc-gateway-port={{beacon_api_port}}
  --enable-debug-rpc-endpoints
  {% if (use_premerge_network) %}
  --execution-endpoint="{{eth1endpoint_premerge}}"
  --terminal-total-difficulty-override={{merge_terminal_total_difficulty}}
  {% else %}
  --execution-endpoint="{{eth1endpoint}}"
  --jwt-secret=/custom_config_data/jwtsecret
  {% endif %}
  {% if (enable_debug_public) %}
  --enable-debug-rpc-endpoints
  {% endif %}

validator_start_args: >
  --accept-terms-of-use=true
  --datadir="/validatordata"
  --chain-config-file="/custom_config_data/config.yaml"
  --beacon-rpc-provider={{beacon_endpoint}}
  --monitoring-host=0.0.0.0 --monitoring-port={{validator_metrics_port}}
  --graffiti="{{graffiti}}"
  --verbosity="{{ validator_log_level | default('info') }}"
  --wallet-dir=/validatordata/wallet
  --wallet-password-file="/validatordata/wallet_pass.txt"
##############################################
# memory limits
##############################################
validator_memory: 2000M
beacon_memory: 5000M

##############################################
# file permissions and user ids
##############################################
keystores_file_mode: "0700"
beacon_user_id: "1000:1000"
validator_user_id: "1000:1000"

separate_validator_process_enabled: true