##############################################
# execution client
##############################################
eth1_client_name: geth
eth1_image_name: ethereum/client-go:stable
eth1_container_name: postmergeel
eth1_data_dir: "/var/lib/goethereum"
eth1_node_dir: "{{home_dir}}/eth1data"   # NOT Hidden folder so its deleted on wipe
eth1_volumes:
  - "{{testnet_dir}}:/networkdata"
  - "{{eth1_node_dir}}:{{eth1_data_dir}}"
  - "{{testnet_dir}}/el_jwtsecret:/jwtsecret"
eth1_memory: 5000M
eth1_user_id: "1000:1000"
geth_init_args: >
  --datadir={{eth1_data_dir}} init /networkdata/genesis.json
eth1_start_args: >
   --networkid={{ POSTMERGE_CHAIN_ID }} 
   --datadir {{eth1_data_dir}}
   --http --http.api "admin,engine,net,eth" 
   --http.port {{ eth1_rpc_port }} 
   --http.addr 0.0.0.0 
   --http.vhosts=*
   --http.corsdomain "*" 
   --ws --ws.api "engine,net,eth" 
   --ws.port {{ eth1_ws_rpc_port }} 
   --ws.addr 0.0.0.0
   --authrpc.port={{ eth1_auth_rpc_port }}
   --authrpc.addr=0.0.0.0
   --authrpc.vhosts=*
   --authrpc.jwtsecret=/jwtsecret
   --nat extip:{{ public_ip_address }}
   --allow-insecure-unlock
   --metrics
   --pprof
   --pprof.addr 0.0.0.0
   --pprof.port={{ eth1_pprof_port }}
   --vmodule=rpc=5
   --maxpeers=75
   {% if (el_bootnode_enode is defined) and el_bootnode_enode %}
   --bootnodes="{{ el_bootnode_enode | join(',') }}"
   {% endif %}  
