loki_bucket: bucket_name
loki_bucket_endpoint: endpoint_url
loki_bucket_access_key: access_key
loki_bucket_secret_key: access_secret

thanos_bucket: bucket_name
thanos_bucket_endpoint: endpoint_url
thanos_bucket_access_key: access_key
thanos_bucket_secret_key: access_secret

acme_email: admin@example.com
cloudflare_email: admin@example.com
cloudflare_dns_api_token: XXXXXXXX

traefik_web_port: 443
traefik_web_http_port: 80

grafana_port: 3000
grafana_client: grafana-test
grafana_host: grafana-test
grafana_domain: example.com
grafana_admin_username: admin
grafana_admin_password: foobar

grafana_github_client_id: client_id
grafana_github_client_secret: client_secret
grafana_github_organizations: organization


##############################################
# Keys generation
##############################################
CL_CHECKPOINT_SYNC: https://goerli.checkpoint-sync.ethpandaops.io
CL_CHECKPOINT_SYNC_TEKU: https://goerli.checkpoint-sync.ethpandaops.io/eth/v2/debug/beacon/states/finalized
ETH1_FROM_ADDR: "0xXXXXX"
ETH1_FROM_PRIV: "XXXXX"

# Generate new transaction hash by deploying a new contract
# TX_HASH: "new"

# Use provided transaction hash
TX_HASH: "0XXXXXX"

MIN_GENESIS_TIME_ADD_SECONDS: 1800
VALIDATORS_PER_INSTANCE: 100
PRYSM_PASSWORD: "prysm"
GENESIS_DELAY: 86400
MIN_GENESIS_TIME: 1645192800
NETWORK: goerli
DEPOSIT_CHAIN_ID: 5
DEPOSIT_NETWORK_ID: 5
POSTMERGE_CHAIN_ID: 1337335

PACKET_LOSS_METHOD: 1   # 0=> Remove all packet loss  1=> Use percentage loss   2=> Use delay loss
PACKET_LOSS_PERCENT: 5 # Use either 5/10/25
PACKET_DELAY_MS: 0

#FORMAT ['TESTNAME', 'SLOTTIME', 'PEERING true OR false', 'postmerge|premerge']
TESTS:
  test1: ['32nodes-premerge1-12s-slottime', 12, 'true', 'postmerge']
  test2: ['32nodes-postmerge2-6s-slottime', 12, 'true', 'premerge']
