loki_bucket: bucket_name
loki_bucket_endpoint: endpoint_url
loki_bucket_access_key: access_key
loki_bucket_secret_key: access_secret

thanos_bucket: bucket_name
thanos_bucket_endpoint: endpoint_url
thanos_bucket_access_key: access_key
thanos_bucket_secret_key: access_secret

acme_email: admin@example.com
cloudflare_email: admin@example.com
cloudflare_dns_api_token: XXXXXXXX

traefik_web_port: 443
traefik_web_http_port: 80

grafana_port: 3000
grafana_client: grafana-test
grafana_host: grafana-test
grafana_domain: example.com
grafana_admin_username: admin
grafana_admin_password: foobar

grafana_github_client_id: client_id
grafana_github_client_secret: client_secret
grafana_github_organizations: organization


##############################################
# Keys generation
##############################################
ETH1_FROM_ADDR: "0xXXXXXXXXX"
ETH1_FROM_PRIV: "XXXXXX"
# Generate new transaction hash by deploying a new contract
# TX_HASH: "new"
# Use provided transaction hash
TX_HASH: "0xXXXXXX"
VALIDATORS_PER_INSTANCE: 100
PRYSM_PASSWORD: "prysm"
