loki_bucket: bucket_name
loki_bucket_endpoint: endpoint_url
loki_bucket_access_key: access_key
loki_bucket_secret_key: access_secret

thanos_bucket: bucket_name
thanos_bucket_endpoint: endpoint_url
thanos_bucket_access_key: access_key
thanos_bucket_secret_key: access_secret

grafana_admin_username: admin
grafana_admin_password: foobar