server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: warn

positions:
  filename: /mnt/config/positions.yml

clients:
  - url: ##promtail_loki_url##

scrape_configs:
- job_name: containers
  static_configs:
  - targets:
      - localhost
    labels:
      host_node: ##inventory_hostname##
      __path__: /var/lib/docker/containers/*/*log

  pipeline_stages:
  - json:
      expressions:
        output: log
        stream: stream
        attrs:

  - json:
      expressions:
        tag:
      source: attrs

  - regex:
      expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|])).(?P<testnet>(?:[^|]*[^|]))
      source: tag

  - timestamp:
      format: RFC3339Nano
      source: time

  - labels:
      stream:
      container_name:
      testnet:

  - labeldrop:
    - filename

  - output:
      source: output

