{
 "title": "Testnet Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "testnet", "label": "Testnet", "query": { "query": "label_values(testnet)" } }
  ]
 },
 "panels": [
  {
   "title": "Peers Per Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Peers Per Client Lighthouse",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "avg(libp2p_peers_per_client{testnet=\"$testnet\"}) by (host_node, Client)",
       "legendFormat": "{{Client}} - {{host_node}}"
      }
     ]
    },
    {
     "title": "Peers Per Client Nimbus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "avg(libp2p_peers_identity{testnet=\"$testnet\"}) by (host_node, agent) ",
       "legendFormat": "{{agent}} - {{host_node}}"
      }
     ]
    },
    {
     "title": "Peers Per Client Teku",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "avg(libp2p_connected_peers_current{testnet=\"$testnet\", host_node=~\".*teku.*\"}) by (host_node, client)",
       "legendFormat": "{{client}} - {{host_node}}"
      }
     ]
    },
    {
     "title": "Peers Per Client Prysm",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "avg(connected_libp2p_peers{testnet=\"$testnet\", host_node=~\".*prysm.*\"}) by (host_node, agent)",
       "legendFormat": "{{agent}} - {{host_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Clients Resources Usage Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy",
     "type": "gauge",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 11, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=~\".*lighthouse.*\",job=\"node-exporter\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\".*lighthouse.*\",job=\"node-exporter\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=~\".*lighthouse.*\",job=\"node-exporter\"}) by (cpu))",
       "legendFormat": "Lighthouse"
      },
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=~\".*prysm.*\",job=\"node-exporter\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\".*prysm.*\",job=\"node-exporter\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=~\".*prysm.*\",job=\"node-exporter\"}) by (cpu))",
       "legendFormat": "Prysm"
      },
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=~\".*nimbus.*\",job=\"node-exporter\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\".*nimbus.*\",job=\"node-exporter\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=~\".*nimbus.*\",job=\"node-exporter\"}) by (cpu))",
       "legendFormat": "Nimbus"
      },
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=~\".*teku.*\",job=\"node-exporter\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\".*teku.*\",job=\"node-exporter\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=~\".*teku.*\",job=\"node-exporter\"}) by (cpu))",
       "legendFormat": "Teku"
      }
     ]
    },
    {
     "title": "Sys Load (5m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (5 min average)",
     "gridPos": { "h": 11, "w": 4, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load5{instance=~\".*lighthouse.*\",job=\"node-exporter\"}) /  count(count(node_cpu_seconds_total{instance=~\".*lighthouse.*\",job=\"node-exporter\"}) by (cpu)) * 100",
       "legendFormat": "Lighthouse"
      },
      {
       "expr": "avg(node_load5{instance=~\".*prysm.*\",job=\"node-exporter\"}) /  count(count(node_cpu_seconds_total{instance=~\".*prysm.*\",job=\"node-exporter\"}) by (cpu)) * 100",
       "legendFormat": "Prysm"
      },
      {
       "expr": "avg(node_load5{instance=~\".*nimbus.*\",job=\"node-exporter\"}) /  count(count(node_cpu_seconds_total{instance=~\".*nimbus.*\",job=\"node-exporter\"}) by (cpu)) * 100",
       "legendFormat": "Nimbus"
      },
      {
       "expr": "avg(node_load5{instance=~\".*teku.*\",job=\"node-exporter\"}) /  count(count(node_cpu_seconds_total{instance=~\".*teku.*\",job=\"node-exporter\"}) by (cpu)) * 100",
       "legendFormat": "Teku"
      }
     ]
    },
    {
     "title": "Sys Load (15m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (15 min average)",
     "gridPos": { "h": 11, "w": 4, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load15{instance=~\".*lighthouse.*\",job=\"node-exporter\"}) /  count(count(node_cpu_seconds_total{instance=~\".*lighthouse.*\",job=\"node-exporter\"}) by (cpu)) * 100",
       "legendFormat": "Lighthouse"
      },
      {
       "expr": "avg(node_load15{instance=~\".*prysm.*\",job=\"node-exporter\"}) /  count(count(node_cpu_seconds_total{instance=~\".*prysm.*\",job=\"node-exporter\"}) by (cpu)) * 100",
       "legendFormat": "Prysm"
      },
      {
       "expr": "avg(node_load15{instance=~\".*nimbus.*\",job=\"node-exporter\"}) /  count(count(node_cpu_seconds_total{instance=~\".*nimbus.*\",job=\"node-exporter\"}) by (cpu)) * 100",
       "legendFormat": "Nimbus"
      },
      {
       "expr": "avg(node_load15{instance=~\".*teku.*\",job=\"node-exporter\"}) /  count(count(node_cpu_seconds_total{instance=~\".*teku.*\",job=\"node-exporter\"}) by (cpu)) * 100",
       "legendFormat": "Teku"
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 11, "w": 4, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - avg((node_memory_MemAvailable_bytes{instance=~\".*lighthouse.*\",job=\"node-exporter\"} * 100) / (node_memory_MemTotal_bytes{instance=~\".*lighthouse.*\",job=\"node-exporter\"}))",
       "legendFormat": "Lighthouse"
      },
      {
       "expr": "100 - avg((node_memory_MemAvailable_bytes{instance=~\".*prysm.*\",job=\"node-exporter\"} * 100) / (node_memory_MemTotal_bytes{instance=~\".*prysm.*\",job=\"node-exporter\"}))",
       "legendFormat": "Prysm"
      },
      {
       "expr": "100 - avg((node_memory_MemAvailable_bytes{instance=~\".*nimbus.*\",job=\"node-exporter\"} * 100) / (node_memory_MemTotal_bytes{instance=~\".*nimbus.*\",job=\"node-exporter\"}))",
       "legendFormat": "Nimbus"
      },
      {
       "expr": "100 - avg((node_memory_MemAvailable_bytes{instance=~\".*teku.*\",job=\"node-exporter\"} * 100) / (node_memory_MemTotal_bytes{instance=~\".*teku.*\",job=\"node-exporter\"}))",
       "legendFormat": "Teku"
      }
     ]
    },
    {
     "title": "SWAP Used",
     "type": "gauge",
     "description": "Used Swap",
     "gridPos": { "h": 11, "w": 4, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((node_memory_SwapTotal_bytes{instance=~\".*lighthouse.*\",job=\"node-exporter\"} - node_memory_SwapFree_bytes{instance=~\".*lighthouse.*\",job=\"node-exporter\"}) / (node_memory_SwapTotal_bytes{instance=~\".*lighthouse.*\",job=\"node-exporter\"} )) * 100",
       "legendFormat": "Lighthouse"
      },
      {
       "expr": "avg((node_memory_SwapTotal_bytes{instance=~\".*prysm.*\",job=\"node-exporter\"} - node_memory_SwapFree_bytes{instance=~\".*prysm.*\",job=\"node-exporter\"}) / (node_memory_SwapTotal_bytes{instance=~\".*prysm.*\",job=\"node-exporter\"} )) * 100",
       "legendFormat": "Prysm"
      },
      {
       "expr": "avg((node_memory_SwapTotal_bytes{instance=~\".*nimbus.*\",job=\"node-exporter\"} - node_memory_SwapFree_bytes{instance=~\".*nimbus.*\",job=\"node-exporter\"}) / (node_memory_SwapTotal_bytes{instance=~\".*nimbus.*\",job=\"node-exporter\"} )) * 100",
       "legendFormat": "Nimbus"
      },
      {
       "expr": "avg((node_memory_SwapTotal_bytes{instance=~\".*teku.*\",job=\"node-exporter\"} - node_memory_SwapFree_bytes{instance=~\".*teku.*\",job=\"node-exporter\"}) / (node_memory_SwapTotal_bytes{instance=~\".*teku.*\",job=\"node-exporter\"} )) * 100",
       "legendFormat": "Teku"
      }
     ]
    },
    {
     "title": "Root FS Used",
     "type": "gauge",
     "description": "Used Root FS",
     "gridPos": { "h": 11, "w": 4, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - avg((node_filesystem_avail_bytes{instance=~\".*lighthouse.*\",job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\".*lighthouse.*\",job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"})",
       "legendFormat": "Lighthouse"
      },
      {
       "expr": "100 - avg((node_filesystem_avail_bytes{instance=~\".*prysm.*\",job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\".*prysm.*\",job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"})",
       "legendFormat": "Prysm"
      },
      {
       "expr": "100 - avg((node_filesystem_avail_bytes{instance=~\".*nimbus.*\",job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\".*nimbus.*\",job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"})",
       "legendFormat": "Nimbus"
      },
      {
       "expr": "100 - avg((node_filesystem_avail_bytes{instance=~\".*teku.*\",job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\".*teku.*\",job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"})",
       "legendFormat": "Teku"
      }
     ]
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Slot Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(slotclock_slot_time_seconds{testnet=\"$testnet\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - avg(process_start_time_seconds{testnet=\"$testnet\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg. Peer Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(libp2p_peers{appname=\"beacon\",testnet=\"$testnet\",host_node=~\".*lighthouse.*\"})",
     "legendFormat": "Lighthouse"
    },
    {
     "expr": "avg(p2p_peer_count{appname=\"beacon\",testnet=\"$testnet\",host_node=~\".*prysm.*\", state=\"Connected\"})",
     "legendFormat": "Prysm"
    },
    {
     "expr": "avg(libp2p_peers{appname=\"beacon\",testnet=\"$testnet\",host_node=~\".*nimbus.*\"})",
     "legendFormat": "Nimbus"
    },
    {
     "expr": "avg(libp2p_peers{appname=\"beacon\",testnet=\"$testnet\",host_node=~\".*teku.*\"})",
     "legendFormat": "Teku"
    }
   ]
  },
  {
   "title": "Avg. VC Genesis Distance Sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vc_genesis_distance_seconds{testnet=\"$testnet\", appname=\"validator\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slotclock Present epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(slotclock_present_epoch{testnet=\"$testnet\", appname=\"beacon\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Justified epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(beacon_current_justified_epoch{testnet=\"$testnet\", appname=\"beacon\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "max(beacon_current_justified_epoch{testnet=\"$testnet\", appname=\"beacon\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Current finalized epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(beacon_finalized_epoch{testnet=\"$testnet\", appname=\"beacon\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "max(beacon_finalized_epoch{testnet=\"$testnet\", appname=\"beacon\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Client Build Versions in order Lighthouse/Prysm/Nimbus/Teku",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(version) (lighthouse_info{testnet=\"$testnet\", host_node=~\".*lighthouse.*\"})",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "max by(version) (prysm_version{testnet=\"$testnet\", host_node=~\".*prysm.*\"})",
     "legendFormat": "Prysm: {{version}}"
    },
    {
     "expr": "max by(version) (version{testnet=\"$testnet\", host_node=~\".*nimbus.*\"})",
     "legendFormat": "Nimbus: {{version}}"
    },
    {
     "expr": "max by(version) (beacon_teku_version{testnet=\"$testnet\", host_node=~\".*teku.*\"})",
     "legendFormat": "Teku: {{version}}"
    }
   ]
  },
  {
   "title": "Avg. VC Attesters",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vc_beacon_attester_count{testnet=\"$testnet\", task=\"current_epoch\", appname=\"validator\"})"
    }
   ]
  },
  {
   "title": "Current slot",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(beacon_head_slot{testnet=\"$testnet\", appname=\"beacon\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "max(beacon_head_slot{testnet=\"$testnet\", appname=\"beacon\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Current active validators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(beacon_current_active_validators{testnet=~\"$testnet\", appname=\"beacon\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg. Beacon Obsv Attesters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(beacon_attn_observation_epoch_attesters{testnet=\"$testnet\", appname=\"beacon\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reorgs Total Prysm",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(beacon_reorgs_total{testnet=\"$testnet\",host_node=~\".*prysm.*\"})",
     "legendFormat": "AVG"
    },
    {
     "expr": "min(beacon_reorgs_total{testnet=\"$testnet\",host_node=~\".*prysm.*\"})",
     "legendFormat": "MIN"
    },
    {
     "expr": "max(beacon_reorgs_total{testnet=\"$testnet\",host_node=~\".*prysm.*\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Reorgs Total Teku",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(beacon_reorgs_total{testnet=\"$testnet\",host_node=~\".*teku.*\"})",
     "legendFormat": "AVG"
    },
    {
     "expr": "min(beacon_reorgs_total{testnet=\"$testnet\",host_node=~\".*teku.*\"})",
     "legendFormat": "MIN"
    },
    {
     "expr": "max(beacon_reorgs_total{testnet=\"$testnet\",host_node=~\".*teku.*\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Average # of processed deposits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(beacon_processed_deposits_total{testnet=~\"$testnet\", appname=\"beacon\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending deposits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(beacon_pending_deposits{testnet=\"$testnet\", appname=\"beacon\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reorgs Total Nimbus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(beacon_reorgs_total{testnet=\"$testnet\",host_node=~\".*nimbus.*\"})",
     "legendFormat": "AVG"
    },
    {
     "expr": "min(beacon_reorgs_total{testnet=\"$testnet\",host_node=~\".*nimbus.*\"})",
     "legendFormat": "MIN"
    },
    {
     "expr": "max(beacon_reorgs_total{testnet=\"$testnet\",host_node=~\".*nimbus.*\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Reorgs Total Lighthouse",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(beacon_reorgs_total{testnet=\"$testnet\",host_node=~\".*lighthouse.*\"})",
     "legendFormat": "AVG"
    },
    {
     "expr": "min(beacon_reorgs_total{testnet=\"$testnet\",host_node=~\".*lighthouse.*\"})",
     "legendFormat": "MIN"
    },
    {
     "expr": "max(beacon_reorgs_total{testnet=\"$testnet\",host_node=~\".*lighthouse.*\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "libp2p_peers{testnet=\"$testnet\", appname=\"beacon\"}",
     "legendFormat": "{{host_node}}"
    },
    {
     "expr": "p2p_peer_count{testnet=\"$testnet\", appname=\"beacon\", state=\"Connected\", host_node=~\".*prysm.*\"}",
     "legendFormat": "{{host_node}}"
    }
   ]
  },
  {
   "title": "Slot drift from expect slot",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 18 },
   "targets": [
    {
     "expr": "slotclock_present_slot{testnet=\"$testnet\", appname=\"beacon\"} - beacon_head_state_slot{testnet=\"$testnet\", appname=\"beacon\"}",
     "legendFormat": "{{host_node}}"
    }
   ]
  },
  {
   "title": "Attestation Percentage  Grapgh",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "beacon_previous_live_validators{testnet=\"$testnet\", host_node=~\".*teku.*\", appname=\"beacon\"}\n/\nbeacon_previous_active_validators{testnet=\"$testnet\", host_node=~\".*teku.*\", appname=\"beacon\"}",
     "legendFormat": "{{host_node}}"
    },
    {
     "expr": "beacon_prev_epoch_target_gwei{testnet=\"$testnet\", host_node=~\".*prysm.*\", appname=\"beacon\"}\n/\nbeacon_prev_epoch_active_gwei{testnet=\"$testnet\", host_node=~\".*prysm.*\", appname=\"beacon\"}",
     "legendFormat": "{{host_node}}"
    },
    {
     "expr": "beacon_current_active_validators{testnet=\"$testnet\", host_node=~\".*nimbus.*\", appname=\"beacon\"}\n/\nbeacon_active_validators{testnet=\"$testnet\", host_node=~\".*nimbus.*\", appname=\"beacon\"}",
     "legendFormat": "{{host_node}}"
    },
    {
     "expr": "beacon_participation_prev_epoch_target_attesting_gwei_total{testnet=\"$testnet\", host_node=~\".*lighthouse.*\", appname=\"beacon\"}\n/\nbeacon_participation_prev_epoch_active_gwei_total{testnet=\"$testnet\", host_node=~\".*lighthouse.*\", appname=\"beacon\"}",
     "legendFormat": "{{host_node}}"
    }
   ]
  },
  {
   "title": "Chain health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Epoch aggregators",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "beacon_attn_observation_epoch_aggregators{testnet=\"$testnet\"}",
       "legendFormat": "{{host_node}}"
      }
     ]
    },
    {
     "title": "re-orgs/min",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 13, "x": 11, "y": 41 },
     "targets": [
      {
       "expr": "increase(beacon_reorgs_total{testnet=\"$testnet\", appname=\"beacon\"} [1m])",
       "legendFormat": "{{host_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg RAM usage - All machines",
     "type": "timeseries",
     "description": "All clients - 16GB RAM",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (host_node) (100 * ((node_memory_MemAvailable_bytes{} - node_memory_MemFree_bytes{} )/ node_memory_MemAvailable_bytes{}))",
       "legendFormat": "{{host_node}}"
      }
     ]
    },
    {
     "title": "Avg CPU usage - All nodes",
     "type": "timeseries",
     "description": "All clients - 8 AMD vCPU cores\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by(host_node) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100) ",
       "legendFormat": "{{host_node}}"
      }
     ]
    },
    {
     "title": "Avg Disk usage - All",
     "type": "timeseries",
     "description": "\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(avg by(host_node)(100 - (node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}))",
       "legendFormat": "{{host_node}}"
      }
     ]
    }
   ]
  },
  { "title": "Slot and Epoch information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Head slot",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "beacon_head_slot{testnet=\"$testnet\", appname=\"beacon\"}",
     "legendFormat": "{{host_node}}"
    }
   ]
  },
  {
   "title": "Present Epoch",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "slotclock_present_epoch{testnet=\"$testnet\", appname=\"beacon\"}",
     "legendFormat": "{{host_node}}"
    },
    {
     "expr": "beacon_current_epoch{testnet=\"$testnet\", appname=\"beacon\"}",
     "legendFormat": "{{host_node}}"
    },
    {
     "expr": "beacon_epoch{testnet=\"$testnet\", appname=\"beacon\"}",
     "legendFormat": "{{host_node}}"
    }
   ]
  },
  {
   "title": "Finalized epoch",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "beacon_finalized_epoch{testnet=\"$testnet\", appname=\"beacon\"}",
     "legendFormat": "{{host_node}}"
    }
   ]
  },
  {
   "title": "Current justified epoch",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "beacon_current_justified_epoch{testnet=\"$testnet\", appname=\"beacon\"}",
     "legendFormat": "{{host_node}}"
    }
   ]
  },
  {
   "title": "Previous justified epoch",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "beacon_previous_justified_epoch{testnet=\"$testnet\", appname=\"beacon\"}",
     "legendFormat": "{{host_node}}"
    }
   ]
  },
  {
   "title": "Current Active Validators Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "beacon_current_active_validators{testnet=\"$testnet\", appname=\"beacon\"}",
     "legendFormat": "{{host_node}}"
    }
   ]
  },
  {
   "title": "Beacon re-orgs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "beacon_reorgs_total{testnet=\"$testnet\", appname=\"beacon\"}",
     "legendFormat": "{{host_node}}"
    }
   ]
  },
  {
   "title": "Block processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block processing time (lighthose)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "rate(beacon_block_processing_seconds_sum{testnet=\"$testnet\", appname=\"beacon\"}[30s])\n/\nrate(beacon_block_processing_seconds_count{testnet=\"$testnet\", appname=\"beacon\"}[30s])",
       "legendFormat": "{{host_node}}"
      }
     ]
    },
    {
     "title": "Syncing slots per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 44 },
     "targets": [
      {
       "expr": "sync_slots_per_second{testnet=\"$testnet\", appname=\"beacon\"}",
       "legendFormat": "{{host_node}}"
      }
     ]
    }
   ]
  }
 ]
}