- name: Global logging firewall management
  hosts: [globalfederation]
  gather_facts: false
  become: true
  vars:
    specific_ips: []

  tasks:
    - name: Reset UFW
      ufw:
        state: reset
        
    - name: Gets Specific IPs
      set_fact: 
        specific_ips: "{{ specific_ips }} + [ '{{ hostvars[item]['ansible_host'] }}/32' ]"
      when: hostvars[item]['rw_host'] == inventory_hostname
      with_items:  "{{ groups['dclocal'] }}"

    # - name: Display Specific IPs
    #   debug: 
    #     var: specific_ips

    - name: Allow ports through firewall
      ufw:
        rule: allow
        port: "{{ item.0 }}"
        proto: "{{ item.1 }}"
        comment: "{{ item.2 }}"
      loop:
        - ["22", "tcp", "Allow SSH"]
        - ["80", "tcp", "Allow HTTP"]
        - ["443", "tcp", "Allow HTTPS"]
        - ["3000", "tcp", "Allow Grafana"]

    - name: Allow ports through firewall from specific hosts
      ufw:
        rule: allow
        src: "{{ item[0] }}"
        port: "{{ item[1] }}"
        proto: "{{ item[2] }}"
        comment: "{{ item[3] }}"
      with_nested:
        - "{{ specific_ips }}"
        - [
            ["3100", "tcp", "Alow Loki Receive"],
            ["10903", "tcp", "Allow thanos receive"]
          ]

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny
        logging: 'on'
