# Custom testnet config

# Extends the mainnet preset
PRESET_BASE: 'mainnet'
CONFIG_NAME: '##CONFIG_NAME##'

# Genesis
# ---------------------------------------------------------------
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: ##MIN_GENESIS_ACTIVE_VALIDATOR_COUNT##
# ##DATE_FULL##
MIN_GENESIS_TIME: ##MIN_GENESIS_TIME##
GENESIS_FORK_VERSION: 0x70000069
# ##GENESIS_DELAY## seconds
GENESIS_DELAY: ##GENESIS_DELAY##


# Forking
# ---------------------------------------------------------------
# Some forks are disabled for now:
#  - These may be re-assigned to another fork-version later
#  - Temporarily set to max uint64 value: 2**64 - 1

# Altair
ALTAIR_FORK_VERSION: 0x70000070
ALTAIR_FORK_EPOCH: 50

# Bellatrix
BELLATRIX_FORK_VERSION: 0x70000071
BELLATRIX_FORK_EPOCH: 150
# TERMINAL_TOTAL_DIFFICULTY: 20000000000000
# TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
# TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615

# Capella
CAPELLA_FORK_VERSION: 0x70000072
CAPELLA_FORK_EPOCH: 18446744073709551615

# Sharding
# SHARDING_FORK_VERSION: 0x04000000
# SHARDING_FORK_EPOCH: 18446744073709551615


# Time parameters
# ---------------------------------------------------------------
# ##SECONDS_PER_SLOT## seconds
SECONDS_PER_SLOT: ##SECONDS_PER_SLOT##
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 14
# 2**8 (= 256) epochs ~27 hours
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
# 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD: 256
# 2**11 (= 2,048) Eth1 blocks ~8 hours
ETH1_FOLLOW_DISTANCE: 16


# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
CHURN_LIMIT_QUOTIENT: 65536


# Deposit contract
# ---------------------------------------------------------------
# Ethereum ##NETWORK## testnet
DEPOSIT_CHAIN_ID: ##DEPOSIT_CHAIN_ID##
DEPOSIT_NETWORK_ID: ##DEPOSIT_NETWORK_ID##
DEPOSIT_CONTRACT_ADDRESS: ##DEPOSIT_CONTRACT_ADDRESS##

