---
# unregister beacon and validator for metrics
- import_playbook: tasks/start_unregistermetrics_beacon_validator.yml

# stop any running beacon/validator docker image, remove existing validator keys and beacon node data
- import_playbook: tasks/stop_and_wipe_beacon_and_validator.yml

