---
- name: Stop and clear all containers!!
  hosts: all
  gather_facts: true
  serial: 20
  tasks:
    - name: Stop all containers
      shell: "docker stop $(docker ps -a -q)"
      register: stop_result
      failed_when: "(stop_result.rc >= 1) and not ('requires at least 1 argument' in stop_result.stderr)"

    - name: Remove all containers
      shell: "docker rm $(docker ps -a -q)"
      register: stop_result
      failed_when: "(stop_result.rc >= 1) and not ('requires at least 1 argument' in stop_result.stderr)"

