---
- name: Setup global servers
  hosts: globalfederation
  gather_facts: false
  tasks:
    - name: Include secret variables
      include_vars: "{{secrets_file}}"

    - name: setup hostname
      become: yes
      import_tasks: tasks/setup_hostname.yml

    - name: setups up the machine with docker, updates apt cache
      become: yes
      import_tasks: tasks/setup_tools.yml

    - name: install node_exporter
      import_tasks: tasks/deploy_node_exporter.yml

    - name: install cadvisor
      import_tasks: tasks/start_cadvisor.yml

    - name: start prometheus
      import_tasks: tasks/start_prometheus.yml

    - name: start thanos
      import_tasks: tasks/start_thanos.yml
    
    - name: start promtail
      import_tasks: tasks/start_promtail.yml
      vars:
        promtail_loki_url: "http://{{ loki_container_name }}:3100/loki/api/v1/push"
    
    - name: start loki
      import_tasks: tasks/start_loki.yml
    
    - name: start grafana
      import_tasks: tasks/start_grafana.yml
