---
# setups up the machine with docker, updates apt cache
- import_playbook: tasks/setup_machine.yml
  vars:
    variable_host: "beacon, validator"

# stop any running beacon/validator docker image, remove existing validator keys and beacon node data
- import_playbook: tasks/stop_and_wipe_beacon_and_validator.yml

# creates requisite directories for data and sets permissions
- import_playbook: tasks/mkdatadirs.yml

# uploads validator keys corresponding to the host
#- import_playbook: tasks/upload_validator_keys.yml

# uploads custom chain config and genesis data if needed
- import_playbook: tasks/upload_custom_config_data.yml

# stars beacon node docker container
- import_playbook: tasks/start_beacon.yml

# stars validator docker container
- import_playbook: tasks/start_validator.yml
  when: separate_validator_process_enabled

# install node_exporter
- import_playbook: tasks/deploy_node_exporter.yml
  vars:
    variable_host: "beacon, validator"

# Start prometheus
- import_playbook: tasks/start_prometheus.yml
  vars:
    variable_host: "beacon, validator"
    enable_remote_write: "true"

# register node for metrics
- import_playbook: tasks/start_registermetrics_node.yml
  vars:
    variable_host: "beacon, validator"

# register beacon and validator for metrics
- import_playbook: tasks/start_registermetrics_beacon_validator.yml
