---
- name: Setup DC local servers
  hosts: dclocal
  gather_facts: false
  tasks:
    - name: Include secret variables
      include_vars: "{{secrets_file}}"

    - name: setup hostname
      become: yes
      import_tasks: tasks/setup_hostname.yml

    - name: setups up the machine with docker, updates apt cache
      become: yes
      import_tasks: tasks/setup_tools.yml

    - name: install node_exporter
      import_tasks: tasks/deploy_node_exporter.yml

    - name: install cadvisor
      import_tasks: tasks/start_cadvisor.yml
      
    - name: start prometheus
      import_tasks: tasks/start_prometheus.yml
      vars:
        enable_remote_receiver: "true"
        remote_write_url: "http://{{ hostvars[hostvars[inventory_hostname].rw_host]['public_ip_address'] }}:10903/api/v1/receive" # write to thanos global

    - name: start promtail
      import_tasks: tasks/start_promtail.yml
      vars:
        push_receiver: "true"
        promtail_loki_url: "http://{{ hostvars[hostvars[inventory_hostname].rw_host]['public_ip_address'] }}:3100/loki/api/v1/push"  # write to global
