---
# setups up the machine with docker, updates apt cache
- import_playbook: tasks/setup_machine.yml
  vars:
    variable_host: "dc_local, global_federation"

# install node_exporter
- import_playbook: tasks/deploy_node_exporter.yml
  vars:
    variable_host: "dc_local, global_federation"

# Start prometheus dc local
- import_playbook: tasks/start_prometheus.yml
  vars:
    variable_host: "dc_local"
    enable_remote_write: "true"
    remote_write_to: "thanos"
    enable_remote_receiver: "true"

# Start prometheus global_federation
- import_playbook: tasks/start_prometheus.yml
  vars:
    variable_host: "global_federation"

# Start grafana
- import_playbook: tasks/start_grafana.yml
  vars:
    variable_host: "global_federation"

# register thanos
- import_playbook: tasks/start_thanos.yml
