# ---
# setups up the machine with docker, updates apt cache
- import_playbook: tasks/setup_machine.yml
  vars:
    variable_host: "geth"

# install node_exporter
- import_playbook: tasks/deploy_node_exporter.yml
  vars:
    variable_host: "geth"

# Start prometheus
- import_playbook: tasks/start_prometheus.yml
  vars:
    variable_host: "geth"
    # write to prometheus dc local
    remote_write_url: "http://{{ hostvars[hostvars[inventory_hostname].rw_host]['public_ip_address'] }}:9090/api/v1/write"

# Start geth
- import_playbook: tasks/start_geth.yml
  when: eth1_client == "geth"

# Start besu
- import_playbook: tasks/start_besu.yml
  when: eth1_client == "besu"

# Start nethermind
- import_playbook: tasks/start_nethermind.yml
  when: eth1_client == "nethermind"

# Start promtail
- import_playbook: tasks/start_promtail.yml
  vars:
    variable_host: "geth"
    promtail_loki_url: "http://{{ hostvars[hostvars[inventory_hostname].rw_host]['public_ip_address'] }}:3500/loki/api/v1/push"
