---
- name: Setup global servers
  hosts: globalfederation
  gather_facts: false
  tasks:
    - name: Include secret variables
      include_vars: "{{secrets_file}}"

    - name: start prometheus
      import_tasks: tasks/start_prometheus.yml
      vars:
        enable_remote_receiver: "false"
        remote_write_url: ""
    
    - name: start promtail
      import_tasks: tasks/start_promtail.yml
      vars:
        push_receiver: "false"
        promtail_loki_url: "http://{{ loki_container_name }}:3100/loki/api/v1/push"

    - name: start thanos
      import_tasks: tasks/start_thanos.yml
    
    - name: start loki
      import_tasks: tasks/start_loki.yml
    
    - name: start grafana
      import_tasks: tasks/start_grafana.yml

    - name: Create tmp dir
      file:
        path: "{{home_dir}}/tmp"
        state: directory

    - name: File server
      community.docker.docker_container:
        name: fileserver
        image: halverneus/static-file-server
        ports:
          - "1111:8080"
        volumes:
          - "{{home_dir}}/tmp:/web"
