---
- hosts: ["{{ runningTest + '_beacon' }}", "{{ runningTest + '_validator' }}", "{{ runningTest + '_dclocal' }}"]
  gather_facts: false
  become: true
  tasks:
    - name: Include secret variables
      include_vars: "{{secrets_file}}"

    - name: Reset tc packet control
      command: "tc qdisc del dev eth0 root"
      register: reset_output
      failed_when: reset_output.rc > 2

    - name: Setup packet loss percentage
      command: "tc qdisc add dev eth0 root netem loss {{ PACKET_LOSS_PERCENT }}%"
      when: PACKET_LOSS_PERCENT > 0 and PACKET_LOSS_METHOD == 1

    - name: Setup packet loss delay
      command: "tc qdisc add dev eth0 root netem delay {{ PACKET_DELAY_MS }}ms"
      when: PACKET_DELAY_MS > 0 and PACKET_LOSS_METHOD == 2

