---
- hosts: geth
  gather_facts: false
  tasks:
    - name: Include secret variables
      include_vars: "{{secrets_file}}"
      
    - name: start prometheus
      import_tasks: tasks/start_prometheus.yml
      vars:
        remote_write_url: "http://{{ hostvars[hostvars[inventory_hostname].rw_host]['public_ip_address'] }}:10903/api/v1/receive" # write to thanos global

    - name: start geth
      import_tasks: tasks/start_geth.yml
      when: eth1_client == "geth"

    - name: start promtail
      import_tasks: tasks/start_promtail.yml
      vars:
        promtail_loki_url: "http://{{ hostvars[hostvars[inventory_hostname].rw_host]['public_ip_address'] }}:3100/loki/api/v1/push" # write to global
