---
- name: Setup Machines
  hosts: ["{{ runningTest + '_beacon' }}", "{{ runningTest + '_validator' }}"]
  gather_facts: false
  tasks:
    - name: start prometheus
      import_tasks: tasks/start_prometheus.yml
      vars:
        enable_remote_receiver: "false"
        remote_write_url: "http://{{ hostvars[hostvars[inventory_hostname].rw_host]['public_ip_address'] }}:9090/api/v1/write" # write to prometheus dc local

    - name: start promtail
      import_tasks: tasks/start_promtail.yml
      vars:
        push_receiver: "false"
        promtail_loki_url: "http://{{ hostvars[hostvars[inventory_hostname].rw_host]['public_ip_address'] }}:3500/loki/api/v1/push"  # write to dc local

- name: Initialize bootnode enr file
  hosts: "{{ runningTest + '_beacon' }}[0]"
  connection: local
  gather_facts: false
  tasks:
    - name: Init bootnode
      import_tasks: tasks/init_bootnode_enr.yml

- name: Start bootnode
  hosts: "{{ runningTest + '_dclocal' }}"
  gather_facts: false
  serial: 1
  tasks:
    - name: Include secret variables
      include_vars: "{{secrets_file}}"

    - name: Start bootnode
      import_tasks: tasks/start_bootnode.yml

- name: Beacon setup
  hosts: "{{ runningTest + '_beacon' }}"
  gather_facts: false
  tasks:
    - name: Include secret variables
      include_vars: "{{secrets_file}}"

    - name: uploads custom chain config and genesis data if needed
      import_tasks: tasks/upload_custom_config_data.yml

    - name: Start beacon
      import_tasks: tasks/start_beacon.yml

- name: Validator setup
  hosts: "{{ runningTest + '_validator' }}"
  gather_facts: false
  tasks:
    - name: Include secret variables
      include_vars: "{{secrets_file}}"

    - name: Generate validator keys
      import_tasks: tasks/generate_validator_keys.yml

    - name: Start validator
      import_tasks: tasks/start_validator.yml
      when: separate_validator_process_enabled

