---
# setups up the machine with docker, updates apt cache
- import_playbook: tasks/setup_machine.yml
  vars:
    variable_host: "beacon, validator"

# Initialize bootnode enr file
- import_playbook: tasks/init_bootnode_enr.yml

# Start bootnode
- import_playbook: tasks/start_bootnode.yml

# unregister beacon and validator for metrics
- import_playbook: tasks/start_unregistermetrics_beacon_validator.yml

# stop any running beacon/validator docker image, remove existing validator keys and beacon node data
- import_playbook: tasks/stop_and_wipe_beacon_and_validator.yml

# Generate validator keys
- import_playbook: tasks/generate_validator_keys.yml

# uploads custom chain config and genesis data if needed
- import_playbook: tasks/upload_custom_config_data.yml

# stars beacon node docker container
- import_playbook: tasks/start_beacon.yml

# stars validator docker container
- import_playbook: tasks/start_validator.yml
  when: separate_validator_process_enabled

# install node_exporter
- import_playbook: tasks/deploy_node_exporter.yml
  vars:
    variable_host: "beacon, validator"

# Start prometheus
- import_playbook: tasks/start_prometheus.yml
  vars:
    variable_host: "beacon, validator"
    # write to prometheus dc local
    remote_write_url: "http://{{ hostvars[hostvars[inventory_hostname].rw_host]['public_ip_address'] }}:9090/api/v1/write"

# register beacon and validator for metrics
- import_playbook: tasks/start_registermetrics_beacon_validator.yml

# Start promtail
- import_playbook: tasks/start_promtail.yml
  vars:
    variable_host: "beacon, validator"
    promtail_loki_url: "http://{{ hostvars[hostvars[inventory_hostname].rw_host]['public_ip_address'] }}:3500/loki/api/v1/push"

