---
# setups up the machine with docker, updates apt cache
- import_playbook: tasks/setup_machine.yml
  vars:
    variable_host: "all:!eth1:!global_federation"

# stop any running beacon/validator docker image, remove existing validator keys and beacon node data
- import_playbook: tasks/stop_and_wipe_beacon_and_validator.yml

# creates requisite directories for data and sets permissions
- import_playbook: tasks/mkdatadirs.yml

# uploads validator keys corresponding to the host
#- import_playbook: tasks/upload_validator_keys.yml

# uploads custom chain config and genesis data if needed
- import_playbook: tasks/upload_custom_config_data.yml

# stars beacon node docker container
- import_playbook: tasks/start_beacon.yml

# stars validator docker container
- import_playbook: tasks/start_validator.yml
  when: separate_validator_process_enabled

# install node_exporter and metric pusher
- import_playbook: tasks/deploy_node_exporter_and_metric_pusher.yml
  when: push_metrics_enabled

# stars prometheus
- import_playbook: tasks/start_prometheus.yml

# # stars grafana
# - import_playbook: tasks/start_grafana.yml
