---
- name: Reboot/Shutdown testnet
  hosts: [beacon, validator]
  gather_facts: false
  
  vars_prompt:
    - name: action
      prompt: Which action do you want to do (reboot/shutdown)?
      private: no

  tasks:
    - name: Shutdown testnet
      community.general.shutdown:
      when: action == 'shutdown'

    - name: Reboot testnet
      reboot:
      when: action == 'reboot'
