---
- name: Reboot/Shutdown testnet
  hosts: ["{{ runningTest + '_beacon' }}", "{{ runningTest + '_validator' }}", "{{ runningTest + '_dclocal' }}"]
  gather_facts: false
  
  vars_prompt:
    - name: action
      prompt: Which action do you want to do (reboot/shutdown)?
      private: false

  tasks:
    - name: Shutdown testnet
      community.general.shutdown:
      when: action == 'shutdown'

    - name: Reboot testnet
      reboot:
      when: action == 'reboot'
