---
- name: Initialize bootnode enr file
  hosts: "{{ runningTest + '_beacon' }}[0]"
  connection: local
  gather_facts: false
  tasks:
    - name: Init bootnode
      import_tasks: tasks/init_bootnode_enr.yml

- name: Start bootnode
  hosts: "{{ runningTest + '_dclocal' }}"
  gather_facts: false
  serial: 1
  tasks:
    - name: Include secret variables
      include_vars: "{{secrets_file}}"

    - name: Start bootnode
      import_tasks: tasks/start_bootnode.yml

- name: Beacon setup
  hosts: ["{{ runningTest + '_beacon' }}"]
  gather_facts: false
  tasks:
    - name: Include secret variables
      include_vars: "{{secrets_file}}"

    - name: Start beacon
      import_tasks: tasks/start_beacon.yml

- name: Validator setup
  hosts: ["{{ runningTest + '_validator' }}"]
  gather_facts: false
  tasks:
    - name: Include secret variables
      include_vars: "{{secrets_file}}"
    
    - name: Start validator
      import_tasks: tasks/start_validator.yml
      when: separate_validator_process_enabled  

