---
# Initialize bootnode enr file
- import_playbook: tasks/init_bootnode_enr.yml

# Start bootnode
- import_playbook: tasks/start_bootnode.yml

# unregister beacon and validator for metrics
- import_playbook: tasks/start_unregistermetrics_beacon_validator.yml

# stop any running beacon/validator docker image, remove existing validator keys and beacon node data => Generate validator keys => uploads custom chain config and genesis data if needed
- import_playbook: tasks/stop_and_wipe_beacon_and_validator.yml
- import_playbook: tasks/generate_validator_keys.yml
- import_playbook: tasks/upload_custom_config_data.yml

# stars beacon node docker container
- import_playbook: tasks/start_beacon.yml

# stars validator docker container
- import_playbook: tasks/start_validator.yml
  when: separate_validator_process_enabled

# register beacon and validator for metrics
- import_playbook: tasks/start_registermetrics_beacon_validator.yml

