---
- name: Initialize bootnode enr file
  hosts: "{{ runningTest + '_beacon' }}[0]"
  connection: local
  gather_facts: false
  tasks:
    - name: Init bootnode
      import_tasks: tasks/init_bootnode_enr.yml

- name: Start bootnode
  hosts: "{{ runningTest + '_dclocal' }}"
  gather_facts: false
  serial: 1
  tasks:
    - name: Include secret variables
      include_vars: "{{secrets_file}}"

    - name: Start bootnode
      import_tasks: tasks/start_bootnode.yml

- name: Wipe data & Unregister beacon and validator metrics
  hosts: ["{{ runningTest + '_beacon' }}", "{{ runningTest + '_validator' }}"]
  gather_facts: false
  tasks:
    - name: unregister beacon and validator for metrics
      import_tasks: tasks/start_unregistermetrics_beacon_validator.yml

    - name: stop any running beacon/validator docker image, remove existing validator keys and beacon node data
      import_tasks: tasks/stop_and_wipe_beacon_and_validator.yml

- name: Beacon setup
  hosts: ["{{ runningTest + '_beacon' }}"]
  gather_facts: false
  tasks:
    - name: Include secret variables
      include_vars: "{{secrets_file}}"

    - name: uploads custom chain config and genesis data if needed
      import_tasks: tasks/upload_custom_config_data.yml
        
    - name: Start beacon
      import_tasks: tasks/start_beacon.yml

    - name: register beacon for metrics
      import_tasks: tasks/start_registermetrics_beacon.yml

- name: Validator setup
  hosts: ["{{ runningTest + '_validator' }}"]
  gather_facts: false
  tasks:
    - name: Include secret variables
      include_vars: "{{secrets_file}}"

    - name: Generate validator keys
      import_tasks: tasks/generate_validator_keys.yml

    - name: Start validator
      import_tasks: tasks/start_validator.yml
      when: separate_validator_process_enabled  

    - name: register validator for metrics
      import_tasks: tasks/start_registermetrics_validator.yml

