---
- name: Stop and clear all containers, also remove all data if allowed!!
  hosts: [all]
  gather_facts: false
  
  vars_prompt:
    - name: confirm_containers
      prompt: Do you want to stop and remove all containers (yes/no)?
      private: no

    - name: confirm_data
      prompt: Do you want to remove all data in home directory (yes/no)?
      private: no

    - name: confirm_images
      prompt: Do you want to remove all docker images (yes/no)?
      private: no

  tasks:
    - name: Stop all containers
      shell: "docker stop $(docker ps -a -q)"
      register: stop_result
      failed_when: "(stop_result.rc >= 1) and not ('requires at least 1 argument' in stop_result.stderr)"
      when: confirm_containers == 'yes'

    - name: Remove all containers
      shell: "docker rm $(docker ps -a -q)"
      register: stop_result
      failed_when: "(stop_result.rc >= 1) and not ('requires at least 1 argument' in stop_result.stderr)"
      when: confirm_containers == 'yes'

    - name: Remove all docker images
      shell: "docker rmi $(docker image ls -a -q)"
      register: stop_result
      failed_when: "(stop_result.rc >= 1) and not ('requires at least 1 argument' in stop_result.stderr)"
      when: confirm_images == 'yes'

    - name: Remove data in home directory NB eth1 data wont be removed since default its in hidden folder
      shell: "sudo rm -rf {{home_dir}}/*"
      when: confirm_data == 'yes'
