---
- name: Wipe all!!
  hosts: all
  gather_facts: true
  serial: 20
  tasks:
    - name: Remove all containers
      shell: "docker rm -v -f $(docker ps -a -q)"
      register: stop_result
      failed_when: "(stop_result.rc >= 1) and not ('requires at least 1 argument' in stop_result.stderr)"

    - name: Remove all images
      shell: "docker rmi $(docker image ls -q)"
      register: stop_result_image
      failed_when: "(stop_result_image.rc >= 1) and not ('requires at least 1 argument' in stop_result_image.stderr)"

    - name: Remove all folders
      become: true
      shell: "rm -rf /home/{{ansible_user}}/*"

