eth1_client_name: geth
eth1_image_name: parithoshj/geth:merge-d28b16f

eth1_memory: 5000M
eth1_kernel_memory: 5500M

# bare websocket
eth1endpoint_ws: ws://127.0.0.1:8546

eth1_volumes:
  - "{{eth1_node_dir}}:/eth1data"
  - "{{testnet_dir}}:/networkdata"

geth_init_args: >
  --datadir=/eth1data init /networkdata/genesis.json

eth1_start_args: >
  --datadir=/eth1data
  --networkid=1337201 --catalyst
  --http --http.api "engine,net,eth,consensus"
  --http.port {{eth1_rpc_port}}
  --http.addr 0.0.0.0
  --http.corsdomain "*"
  --ws --ws.api "net,eth,consensus,engine"
  --ws.port={{eth1_ws_rpc_port}}
  --ws.addr 0.0.0.0
  --nat extip:{{ansible_host}}
  --allow-insecure-unlock
  --vmodule=rpc=5
  {% if (eth1_bootnode_enode is defined) and eth1_bootnode_enode %}
  --bootnodes "{{ eth1_bootnode_enode | join(',') }}"
  {% endif %}

eth1_user_id: "1000:1000"
