eth1_client_name: besu
eth1_image_name: suburbandad/besu:merge

eth1_memory: 5000M
eth1_kernel_memory: 5500M

# websocket with /ws suffix
eth1endpoint_ws: ws://127.0.0.1:8546/ws

eth1_volumes:
  - "{{eth1_node_dir}}:/eth1data"
  - "{{testnet_dir}}:/networkdata"

eth1_start_args: >
  --data-path="/eth1data/data"
  --genesis-file="/networkdata/besu_genesis.json"
  --network-id=1337201
  --rpc-http-enabled --rpc-http-api=ETH,NET,DEBUG,EXECUTION
  --rpc-http-host=0.0.0.0
  --rpc-http-port={{eth1_rpc_port}}
  --rpc-http-cors-origins="*"
  --rpc-ws-enabled --rpc-ws-api=ETH,NET,EXECUTION,DEBUG
  --rpc-ws-host=0.0.0.0
  --rpc-ws-port={{eth1_ws_rpc_port}}
  --host-allowlist="*"
  --Xmerge-support=true
  --discovery-enabled=false
  --logging="DEBUG"
  {% if (eth1_bootnode_enode is defined) and bootnode_enrs %}
  --bootnodes="{{ eth1_bootnode_enode | join(',') }}"
  {% endif %}

#  --miner-coinbase="0x1000000000000000000000000000000000000000"

eth1_user_id: "1000:1000"
